// src/views/HomeView.vue
<script setup lang="ts">
import type { NodeData } from '@/stores/nodes'
import { Icon } from '@iconify/vue'
import { useDebounceFn } from '@vueuse/core'
import { computed, defineAsyncComponent, nextTick, onActivated, onDeactivated, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import MarkdownRenderer from '@/components/MarkdownRenderer.vue'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Empty } from '@/components/ui/empty'
import { Input } from '@/components/ui/input'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { useAppStore } from '@/stores/app'
import { useNodesStore } from '@/stores/nodes'
import { isNodeInGroup, parseNodeGroups } from '@/utils/groupHelper'
import { isRegionMatch } from '@/utils/regionHelper'

defineOptions({ name: 'HomeView' })

const NodeCard = defineAsyncComponent(() => import('@/components/NodeCard.vue'))
const NodeGeneralCards = defineAsyncComponent(() => import('@/components/NodeGeneralCards.vue'))
const NodeList = defineAsyncComponent(() => import('@/components/NodeList.vue'))
const PingChart = defineAsyncComponent(() => import('@/components/PingChart.vue'))

const nodeItemStaggerMs = 35
const nodeItemStaggerLimit = 12

const appStore = useAppStore()
const nodesStore = useNodesStore()
const router = useRouter()

onActivated(() => {
  if (appStore.homeScrollPosition > 0) {
    nextTick(() => {
      window.scrollTo({ top: appStore.homeScrollPosition, behavior: 'instant' })
    })
  }
})

onDeactivated(() => {
  appStore.homeScrollPosition = window.scrollY
})

const searchText = ref('')
const debouncedSearchText = ref('')
const selectedPingNodeUuid = ref<string | null>(null)

const updateDebouncedSearch = useDebounceFn((value: string) => {
  debouncedSearchText.value = value
}, 300)

watch(searchText, (value) => {
  updateDebouncedSearch(value)
})

const groups = computed(() => [
  { tab: '全部节点', name: 'all' },
  ...nodesStore.groups.map(g => ({ tab: g, name: g })),
])

watch(
  () => nodesStore.groups,
  (gs) => {
    const cur = appStore.nodeSelectedGroup
    if (cur !== 'all' && !gs.includes(cur)) {
      appStore.nodeSelectedGroup = 'all'
    }
  },
  { immediate: true },
)

function isNodeMatchSearch(node: typeof nodesStore.nodes[number], search: string): boolean {
  if (!search.trim())
    return true
  const lowerSearch = search.toLowerCase().trim()
  if (node.name.toLowerCase().includes(lowerSearch))
    return true
  if (node.region && isRegionMatch(node.region, search))
    return true
  if (node.os && node.os.toLowerCase().includes(lowerSearch))
    return true
  if (parseNodeGroups(node.group).some(group => group.toLowerCase().includes(lowerSearch)))
    return true
  if (node.tags && node.tags.toLowerCase().includes(lowerSearch))
    return true
  if (node.remark && node.remark.toLowerCase().includes(lowerSearch))
    return true
  return false
}

const groupNodeList = computed(() => {
  return nodesStore.nodes.filter(node => isNodeInGroup(node.group, appStore.nodeSelectedGroup))
})

const sampledGroupNodeList = computed(() => {
  return nodesStore.earthNodes.filter(node => isNodeInGroup(node.group, appStore.nodeSelectedGroup))
})

const nodeList = computed(() => {
  let filtered = groupNodeList.value
  if (debouncedSearchText.value.trim()) {
    filtered = filtered.filter(n => isNodeMatchSearch(n, debouncedSearchText.value))
  }
  return filtered
})

const selectedPingNode = computed(() => {
  if (!selectedPingNodeUuid.value)
    return null
  return nodesStore.nodes.find(node => node.uuid === selectedPingNodeUuid.value) ?? null
})

const pingDialogOpen = computed({
  get: () => selectedPingNode.value !== null,
  set: (open: boolean) => {
    if (!open)
      selectedPingNodeUuid.value = null
  },
})

function handleNodeClick(node: typeof nodesStore.nodes[number]) {
  router.push({ name: 'instance-detail', params: { id: node.uuid } })
}

function handlePingClick(node: NodeData) {
  selectedPingNodeUuid.value = node.uuid
}

function getNodeItemTransitionKey(node: typeof nodesStore.nodes[number]): string {
  return `${appStore.nodeSelectedGroup}-${node.uuid}`
}

function getNodeItemTransitionStyle(index: number): Record<string, string> {
  return {
    '--node-item-delay': `${Math.min(index, nodeItemStaggerLimit) * nodeItemStaggerMs}ms`,
  }
}
</script>

<template>
  <div class="home-view">
    <div v-if="appStore.connectionError" class="alert px-4">
      <Alert variant="destructive" class="border-none backdrop-blur-xs bg-red-400/10 rounded-md">
        <AlertTitle>RPC 服务错误</AlertTitle>
        <AlertDescription>连接服务器失败，请检查网络设置或刷新页面后再试。</AlertDescription>
      </Alert>
    </div>

    <div v-if="appStore.alertEnabled && appStore.alertContent" class="alert px-4">
      <Alert class="border-none bg-background/60 backdrop-blur-xs rounded-md">
        <AlertTitle v-if="appStore.alertTitle">
          {{ appStore.alertTitle }}
        </AlertTitle>
        <AlertDescription>
          <MarkdownRenderer :content="appStore.alertContent" />
        </AlertDescription>
      </Alert>
    </div>

    <NodeGeneralCards
      v-if="appStore.earthViewMode !== 'hide'"
      :nodes="groupNodeList"
      :globe-nodes="sampledGroupNodeList"
      :transition-key="appStore.nodeSelectedGroup"
    />

    <div class="node-info p-4 pt-0 flex flex-col gap-4 relative z-1 md:pointer-events-none" :class="appStore.earthViewMode === 'hide' && 'pt-4'">
      <div class="nodes">
        <Tabs v-model="appStore.nodeSelectedGroup" class="w-full flex-col gap-4">
          <div class="flex gap-2 items-start flex-nowrap">
            <div class="overflow-x-auto rounded-sm md:pointer-events-auto">
              <TabsList class="w-max h-8 bg-background/50 backdrop-blur-xl rounded-md">
                <TabsTrigger
                  v-for="g in groups" :key="g.name" :value="g.name"
                  class="h-6.5 flex-none shrink-0 text-xs border-none data-[state=active]:text-green-600 shadow-none rounded-sm"
                >
                  {{ g.tab }}
                </TabsTrigger>
              </TabsList>
            </div>
            <div class="ml-auto search flex gap-2 items-center pointer-events-auto">
              <Button
                variant="outline" size="icon" aria-label="卡片视图"
                class="w-8 h-8 border-none  bg-background/50 backdrop-blur-xs shadow-none hover:bg-background/60 rounded-md"
                :class="[appStore.nodeViewMode === 'card' ? '!text-green-600 !bg-background' : '']"
                @click="appStore.nodeViewMode = 'card'"
              >
                <Icon icon="tabler:layout-grid" :width="14" :height="14" />
              </Button>
              <Button
                variant="outline" size="icon" aria-label="列表视图"
                class="w-8 h-8 border-none bg-background/50 backdrop-blur-xs shadow-none hover:bg-background/60 rounded-md"
                :class="[appStore.nodeViewMode === 'list' ? '!text-green-600 !bg-background' : '']"
                @click="appStore.nodeViewMode = 'list'"
              >
                <Icon icon="tabler:table" :width="14" :height="14" />
              </Button>
              <div class="relative z-1 w-8 h-8">
                <div class="absolute top-0 right-0 ">
                  <Input
                    v-model="searchText" placeholder="搜索节点名称、地区、系统"
                    class="transition-all placeholder:text-transparent border-none shadow-none w-8 h-8  bg-background/50 backdrop-blur-xs rounded-md hover:!bg-background/60 focus:!w-60 focus:!pl-7.5 focus:placeholder:!text-muted-foreground focus:!bg-background/80 focus:!ring-slate-500/10"
                  />
                  <Icon
                    icon="tabler:search" :width="14" :height="14"
                    class="absolute left-2.5 top-1/2 -translate-y-1/2 pointer-events-none"
                  />
                </div>
              </div>
            </div>
          </div>
          <TabsContent :key="appStore.nodeSelectedGroup" :value="appStore.nodeSelectedGroup" class="pointer-events-auto">
            <TransitionGroup
              v-if="nodeList.length !== 0 && appStore.nodeViewMode === 'card'"
              :appear="!appStore.disablePageAnimation"
              :css="!appStore.disablePageAnimation"
              name="node-card-switch"
              tag="div"
              class="gap-3 grid grid-cols-1 sm:grid-cols-[repeat(auto-fill,minmax(300px,1fr))]"
            >
              <div
                v-for="(node, index) in nodeList"
                :key="getNodeItemTransitionKey(node)"
                class="min-w-0"
                :style="getNodeItemTransitionStyle(index)"
              >
                <NodeCard :node="node" @click="handleNodeClick(node)" @ping-click="handlePingClick" />
              </div>
            </TransitionGroup>
            <NodeList
              v-else-if="nodeList.length !== 0 && appStore.nodeViewMode === 'list'"
              :nodes="nodeList"
              :transition-key="appStore.nodeSelectedGroup"
              @click="handleNodeClick"
              @ping-click="handlePingClick"
            />
            <div v-else class="text-muted-foreground text-center py-8">
              <Empty description="暂无节点" />
            </div>
          </TabsContent>
        </Tabs>
      </div>
    </div>

    <Dialog v-model:open="pingDialogOpen">
      <DialogContent
        v-if="selectedPingNode"
        class="max-w-6xl gap-0 overflow-hidden bg-background/60 p-0 shadow-[0_0_2rem_rgba(0,0,0,0.1)]"
        overlay-class="bg-background/30"
      >
        <DialogHeader class="flex h-13 flex-row items-center px-4">
          <DialogTitle class="truncate">
            {{ selectedPingNode.name }} 延迟 / 丢包
          </DialogTitle>
        </DialogHeader>
        <div class="max-h-[calc(90vh-4rem)] overflow-y-auto p-4 pt-0">
          <PingChart :uuid="selectedPingNode.uuid" />
        </div>
      </DialogContent>
    </Dialog>
  </div>
</template>

<style scoped>
.node-card-switch-enter-active,
.node-card-switch-leave-active {
  transition:
    opacity 180ms ease,
    transform 220ms cubic-bezier(0.22, 1, 0.36, 1),
    filter 180ms ease;
}

.node-card-switch-enter-active {
  transition-delay: var(--node-item-delay, 0ms);
}

.node-card-switch-move {
  transition: transform 220ms cubic-bezier(0.22, 1, 0.36, 1);
}

.node-card-switch-enter-from {
  opacity: 0;
  transform: translateY(10px) scale(0.985);
  filter: blur(3px);
}

.node-card-switch-leave-to {
  opacity: 0;
  transform: translateY(-6px) scale(0.99);
  filter: blur(2px);
}

@media (prefers-reduced-motion: reduce) {
  .node-card-switch-enter-active,
  .node-card-switch-leave-active,
  .node-card-switch-move {
    transition: none;
    transition-delay: 0ms;
  }

  .node-card-switch-enter-from,
  .node-card-switch-leave-to {
    opacity: 1;
    transform: none;
    filter: none;
  }
}
</style>

// src/views/HomeView.tsx
'use client'

import type { NodeData } from '@/stores/nodes'
import { Icon } from '@iconify/react'
import { useEffect, useMemo, useState } from 'react'
import MarkdownRenderer from '@/components/MarkdownRenderer'
import NodeCard from '@/components/NodeCard'
import NodeGeneralCards from '@/components/NodeGeneralCards'
import NodeList from '@/components/NodeList'
import PingChart from '@/components/PingChart'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Empty } from '@/components/ui/empty'
import { Input } from '@/components/ui/input'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { useAppDerived, useAppStore } from '@/stores/app'
import { selectNodeGroups, useNodesStore } from '@/stores/nodes'
import { isNodeInGroup, parseNodeGroups } from '@/utils/groupHelper'
import { navigateTo } from '@/utils/navigation'
import { isRegionMatch } from '@/utils/regionHelper'

const nodeItemStaggerMs = 35
const nodeItemStaggerLimit = 12

function isNodeMatchSearch(node: NodeData, search: string): boolean {
  if (!search.trim())
    return true
  const lowerSearch = search.toLowerCase().trim()
  if (node.name.toLowerCase().includes(lowerSearch))
    return true
  if (node.region && isRegionMatch(node.region, search))
    return true
  if (node.os && node.os.toLowerCase().includes(lowerSearch))
    return true
  if (parseNodeGroups(node.group).some(group => group.toLowerCase().includes(lowerSearch)))
    return true
  if (node.tags && node.tags.toLowerCase().includes(lowerSearch))
    return true
  if (node.remark && node.remark.toLowerCase().includes(lowerSearch))
    return true
  return false
}

export default function HomeView() {
  const nodes = useNodesStore(state => state.nodes)
  const earthNodes = useNodesStore(state => state.earthNodes)
  const groupsRaw = useMemo(() => selectNodeGroups(nodes), [nodes])
  const connectionError = useAppStore(state => state.connectionError)
  const homeScrollPosition = useAppStore(state => state.homeScrollPosition)
  const setHomeScrollPosition = useAppStore(state => state.setHomeScrollPosition)
  const nodeSelectedGroup = useAppStore(state => state.nodeSelectedGroup)
  const setNodeSelectedGroup = useAppStore(state => state.setNodeSelectedGroup)
  const setNodeViewMode = useAppStore(state => state.setNodeViewMode)
  const derived = useAppDerived()
  const [searchText, setSearchText] = useState('')
  const [debouncedSearchText, setDebouncedSearchText] = useState('')
  const [selectedPingNodeUuid, setSelectedPingNodeUuid] = useState<string | null>(null)

  useEffect(() => {
    const timer = setTimeout(setDebouncedSearchText, 300, searchText)
    return () => clearTimeout(timer)
  }, [searchText])

  useEffect(() => {
    if (homeScrollPosition > 0)
      window.scrollTo({ top: homeScrollPosition, behavior: 'instant' })
    return () => setHomeScrollPosition(window.scrollY)
  }, [homeScrollPosition, setHomeScrollPosition])

  useEffect(() => {
    if (nodeSelectedGroup !== 'all' && !groupsRaw.includes(nodeSelectedGroup))
      setNodeSelectedGroup('all')
  }, [groupsRaw, nodeSelectedGroup, setNodeSelectedGroup])

  const groups = useMemo(() => [
    { tab: '全部节点', name: 'all' },
    ...groupsRaw.map(group => ({ tab: group, name: group })),
  ], [groupsRaw])

  const groupNodeList = useMemo(() => nodes.filter(node => isNodeInGroup(node.group, nodeSelectedGroup)), [nodeSelectedGroup, nodes])
  const sampledGroupNodeList = useMemo(() => earthNodes.filter(node => isNodeInGroup(node.group, nodeSelectedGroup)), [nodeSelectedGroup, earthNodes])
  const nodeList = useMemo(() => {
    let filtered = groupNodeList
    if (debouncedSearchText.trim())
      filtered = filtered.filter(node => isNodeMatchSearch(node, debouncedSearchText))
    return filtered
  }, [debouncedSearchText, groupNodeList])
  const selectedPingNode = selectedPingNodeUuid ? nodes.find(node => node.uuid === selectedPingNodeUuid) ?? null : null

  function handleNodeClick(node: NodeData) {
    navigateTo(`/instance/${encodeURIComponent(node.uuid)}`)
  }

  return (
    <div className="home-view">
      {connectionError
        ? (
            <div className="alert px-4">
              <Alert variant="destructive" className="rounded-md border-none bg-red-400/10 backdrop-blur-xs">
                <AlertTitle>RPC 服务错误</AlertTitle>
                <AlertDescription>连接服务器失败，请检查网络设置或刷新页面后再试。</AlertDescription>
              </Alert>
            </div>
          )
        : null}

      {derived.alertEnabled && derived.alertContent
        ? (
            <div className="alert px-4">
              <Alert className="rounded-md border-none bg-background/60 backdrop-blur-xs">
                {derived.alertTitle ? <AlertTitle>{derived.alertTitle}</AlertTitle> : null}
                <AlertDescription>
                  <MarkdownRenderer content={derived.alertContent} />
                </AlertDescription>
              </Alert>
            </div>
          )
        : null}

      {derived.earthViewMode !== 'hide'
        ? (
            <NodeGeneralCards
              nodes={groupNodeList}
              globeNodes={sampledGroupNodeList}
              transitionKey={nodeSelectedGroup}
            />
          )
        : null}

      <div className={`node-info relative z-1 flex flex-col gap-4 p-4 pt-0 md:pointer-events-none ${derived.earthViewMode === 'hide' ? 'pt-4' : ''}`}>
        <div className="nodes">
          <Tabs value={nodeSelectedGroup} onValueChange={value => setNodeSelectedGroup(String(value))} className="flex w-full flex-col gap-4">
            <div className="flex flex-nowrap items-start gap-2">
              <div className="overflow-x-auto rounded-sm md:pointer-events-auto">
                <TabsList className="h-8 w-max rounded-md bg-background/50 backdrop-blur-xl">
                  {groups.map(group => (
                    <TabsTrigger
                      key={group.name}
                      value={group.name}
                      className="h-6.5 flex-none shrink-0 rounded-sm border-none text-xs shadow-none data-[selected]:text-green-600"
                    >
                      {group.tab}
                    </TabsTrigger>
                  ))}
                </TabsList>
              </div>
              <div className="search pointer-events-auto ml-auto flex items-center gap-2">
                <Button
                  variant="outline"
                  size="icon"
                  aria-label="卡片视图"
                  className={`h-8 w-8 rounded-md border-none bg-background/50 shadow-none backdrop-blur-xs hover:bg-background/60 ${derived.nodeViewMode === 'card' ? '!bg-background !text-green-600' : ''}`}
                  onClick={() => setNodeViewMode('card')}
                >
                  <Icon icon="tabler:layout-grid" width={14} height={14} />
                </Button>
                <Button
                  variant="outline"
                  size="icon"
                  aria-label="列表视图"
                  className={`h-8 w-8 rounded-md border-none bg-background/50 shadow-none backdrop-blur-xs hover:bg-background/60 ${derived.nodeViewMode === 'list' ? '!bg-background !text-green-600' : ''}`}
                  onClick={() => setNodeViewMode('list')}
                >
                  <Icon icon="tabler:table" width={14} height={14} />
                </Button>
                <div className="relative z-1 h-8 w-8">
                  <div className="absolute top-0 right-0">
                    <Input
                      value={searchText}
                      onChange={event => setSearchText(event.target.value)}
                      placeholder="搜索节点名称、地区、系统"
                      className="h-8 w-8 rounded-md border-none bg-background/50 shadow-none backdrop-blur-xs transition-all placeholder:text-transparent hover:!bg-background/60 focus:!w-60 focus:!bg-background/80 focus:!pl-7.5 focus:placeholder:!text-muted-foreground focus:!ring-slate-500/10"
                    />
                    <Icon icon="tabler:search" width={14} height={14} className="pointer-events-none absolute top-1/2 left-2.5 -translate-y-1/2" />
                  </div>
                </div>
              </div>
            </div>
            <TabsContent value={nodeSelectedGroup} className="pointer-events-auto">
              {nodeList.length !== 0 && derived.nodeViewMode === 'card'
                ? (
                    <div className="grid grid-cols-1 gap-3 sm:grid-cols-[repeat(auto-fill,minmax(300px,1fr))]">
                      {nodeList.map((node, index) => (
                        <div
                          key={`${nodeSelectedGroup}-${node.uuid}`}
                          className="min-w-0"
                          style={{ animationDelay: `${Math.min(index, nodeItemStaggerLimit) * nodeItemStaggerMs}ms` }}
                        >
                          <NodeCard node={node} onClick={() => handleNodeClick(node)} onPingClick={node => setSelectedPingNodeUuid(node.uuid)} />
                        </div>
                      ))}
                    </div>
                  )
                : nodeList.length !== 0 && derived.nodeViewMode === 'list'
                  ? (
                      <NodeList
                        nodes={nodeList}
                        transitionKey={nodeSelectedGroup}
                        onClick={handleNodeClick}
                        onPingClick={node => setSelectedPingNodeUuid(node.uuid)}
                      />
                    )
                  : (
                      <div className="py-8 text-center text-muted-foreground">
                        <Empty description="暂无节点" />
                      </div>
                    )}
            </TabsContent>
          </Tabs>
        </div>
      </div>

      <Dialog open={Boolean(selectedPingNode)} onOpenChange={open => !open && setSelectedPingNodeUuid(null)}>
        {selectedPingNode
          ? (
              <DialogContent
                className="max-w-6xl gap-0 overflow-hidden bg-background/60 p-0 shadow-[0_0_2rem_rgba(0,0,0,0.1)]"
                overlayClass="bg-background/30"
              >
                <DialogHeader className="flex h-13 flex-row items-center px-4">
                  <DialogTitle className="truncate">
                    {selectedPingNode.name}
                    {' '}
                    延迟 / 丢包
                  </DialogTitle>
                </DialogHeader>
                <div className="max-h-[calc(90vh-4rem)] overflow-y-auto p-4 pt-0">
                  <PingChart uuid={selectedPingNode.uuid} />
                </div>
              </DialogContent>
            )
          : null}
      </Dialog>
    </div>
  )
}
