// src/components/Background.tsx
'use client'

import { useEffect, useRef, useState } from 'react'
import { useAppDerived } from '@/stores/app'

export default function Background() {
  const derived = useAppDerived()
  const [isLoaded, setIsLoaded] = useState(false)
  const [hasError, setHasError] = useState(false)
  const videoRef = useRef<HTMLVideoElement | null>(null)

  const currentUrl = derived.backgroundEnabled ? derived.currentBackgroundUrl : ''
  const hasCustomBackground = derived.backgroundEnabled && Boolean(currentUrl)
  const showBackgroundOverlay = hasCustomBackground && derived.backgroundOverlay > 0
  const showLoadedBackground = hasCustomBackground && isLoaded && !hasError
  const showMediaBackground = hasCustomBackground && !hasError && (derived.backgroundType === 'video' || showLoadedBackground)
  const showDefaultBackground = !hasCustomBackground
  const showLoadingBackground = hasCustomBackground && !isLoaded && !hasError
  const showFallbackBackground = hasCustomBackground && hasError

  useEffect(() => {
    setIsLoaded(false)
    setHasError(false)

    if (!derived.backgroundEnabled || !currentUrl)
      return undefined

    if (derived.backgroundType !== 'image')
      return undefined

    const image = new Image()
    image.onload = () => {
      setIsLoaded(true)
      setHasError(false)
    }
    image.onerror = () => {
      setIsLoaded(false)
      setHasError(true)
    }
    image.src = currentUrl

    return () => {
      image.onload = null
      image.onerror = null
    }
  }, [currentUrl, derived.backgroundEnabled, derived.backgroundType])

  useEffect(() => {
    if (!derived.backgroundEnabled || !currentUrl) {
      videoRef.current?.pause()
      videoRef.current?.removeAttribute('src')
      videoRef.current?.load()
    }
  }, [currentUrl, derived.backgroundEnabled])

  const containerStyle = hasCustomBackground && derived.backgroundOverlay < 0
    ? { opacity: 1 - Math.abs(derived.backgroundOverlay) / 100 }
    : undefined
  const backgroundStyle = {
    filter: derived.backgroundBlur > 0 ? `blur(${derived.backgroundBlur}px)` : 'none',
    opacity: derived.backgroundType === 'video' && !isLoaded ? 0 : 1,
  }
  const overlayStyle = derived.backgroundOverlay > 0
    ? { backgroundColor: `rgba(0, 0, 0, ${derived.backgroundOverlay / 100})` }
    : undefined

  return (
    <div className="fixed inset-0 -z-10 overflow-hidden" style={containerStyle}>
      {showDefaultBackground
        ? (
            <div className="absolute inset-0 mx-0 max-w-none overflow-hidden zoom-150 bg-slate-50 dark:bg-slate-900/50">
              <div className="absolute top-0 left-1/2 -ml-152 h-100 w-325 dark:mask-[linear-gradient(white,transparent)]">
                <div className="absolute inset-0 bg-linear-to-r from-emerald-500 to-lime-300 opacity-40 mask-[radial-gradient(farthest-side_at_top,white,transparent)] dark:from-emerald-500/30 dark:to-lime-300/30 dark:opacity-100">
                  <svg
                    aria-hidden="true"
                    className="absolute inset-x-0 inset-y-[-50%] h-[200%] w-full skew-y-[-18deg] fill-black/40 stroke-black/50 mix-blend-overlay dark:fill-white/2.5 dark:stroke-white/5"
                  >
                    <defs>
                      <pattern id="_S_1_" width="72" height="56" patternUnits="userSpaceOnUse" x="-12" y="4">
                        <path d="M.5 56V.5H72" fill="none" />
                      </pattern>
                    </defs>
                    <rect width="100%" height="100%" strokeWidth="0" fill="url(#_S_1_)" />
                    <svg x="-12" y="4" className="overflow-visible">
                      <rect strokeWidth="0" width="73" height="57" x="288" y="168" />
                      <rect strokeWidth="0" width="73" height="57" x="144" y="56" />
                      <rect strokeWidth="0" width="73" height="57" x="504" y="168" />
                      <rect strokeWidth="0" width="73" height="57" x="720" y="336" />
                    </svg>
                  </svg>
                </div>
              </div>
            </div>
          )
        : null}
      {showLoadingBackground || showFallbackBackground ? <div className="absolute inset-0 bg-background" /> : null}
      {showMediaBackground
        ? (
            <div className="absolute inset-0 scale-110 transition-opacity duration-700" style={backgroundStyle}>
              {derived.backgroundType === 'image'
                ? (
                    <div
                      className="h-full w-full bg-cover bg-center bg-no-repeat"
                      style={{ backgroundImage: `url(${currentUrl})` }}
                    />
                  )
                : (
                    <video
                      ref={videoRef}
                      className="h-full w-full object-cover"
                      src={currentUrl}
                      autoPlay
                      loop
                      muted
                      preload="auto"
                      playsInline
                      onLoadedData={() => {
                        setIsLoaded(true)
                        setHasError(false)
                      }}
                      onCanPlay={() => {
                        setIsLoaded(true)
                        setHasError(false)
                      }}
                      onError={() => {
                        setIsLoaded(false)
                        setHasError(true)
                      }}
                    />
                  )}
            </div>
          )
        : null}
      {showBackgroundOverlay ? <div className="pointer-events-none absolute inset-0" style={overlayStyle} /> : null}
    </div>
  )
}

// src/components/Background.vue
<script setup lang="ts">
import { computed, onUnmounted, ref, watch } from 'vue'
import { useAppStore } from '@/stores/app'

const appStore = useAppStore()

const isLoaded = ref(false)
const hasError = ref(false)

const backgroundStyle = computed(() => {
  const blur = appStore.backgroundBlur
  return {
    filter: blur > 0 ? `blur(${blur}px)` : 'none',
    opacity: appStore.backgroundType === 'video' && !isLoaded.value ? 0 : 1,
  }
})

const backgroundContainerStyle = computed(() => {
  const overlay = appStore.backgroundOverlay
  if (overlay >= 0)
    return {}

  return { opacity: 1 - Math.abs(overlay) / 100 }
})

const overlayStyle = computed(() => {
  const overlay = appStore.backgroundOverlay
  if (overlay <= 0)
    return {}

  return { backgroundColor: `rgba(0, 0, 0, ${overlay / 100})` }
})

const showBackground = computed(() => appStore.backgroundEnabled)
const showBackgroundOverlay = computed(() => appStore.backgroundOverlay > 0)
const currentUrl = computed(() => appStore.currentBackgroundUrl)
const backgroundType = computed(() => appStore.backgroundType)

const showLoadedBackground = computed(() =>
  showBackground.value && currentUrl.value && isLoaded.value && !hasError.value,
)

const showMediaBackground = computed(() =>
  showBackground.value && currentUrl.value && !hasError.value && (backgroundType.value === 'video' || showLoadedBackground.value),
)

const showDefaultBackground = computed(() => {
  if (!showBackground.value)
    return false
  if (!currentUrl.value)
    return true
  if (hasError.value)
    return true
  return false
})

const showLoadingBackground = computed(() =>
  showBackground.value && currentUrl.value && !isLoaded.value && !hasError.value,
)

let imageLoader: HTMLImageElement | null = null

function clearImageLoader() {
  if (imageLoader) {
    imageLoader.onload = null
    imageLoader.onerror = null
    imageLoader = null
  }
}

function loadImage(url: string) {
  isLoaded.value = false
  hasError.value = false

  clearImageLoader()

  imageLoader = new Image()
  imageLoader.onload = () => {
    isLoaded.value = true
    hasError.value = false
  }
  imageLoader.onerror = () => {
    isLoaded.value = false
    hasError.value = true
  }
  imageLoader.src = url
}

const videoRef = ref<HTMLVideoElement | null>(null)

function handleVideoLoaded() {
  isLoaded.value = true
  hasError.value = false
}
function handleVideoError() {
  isLoaded.value = false
  hasError.value = true
}

watch([currentUrl, backgroundType], ([url, type]) => {
  if (url && type === 'image') {
    loadImage(url)
  }
  else if (url && type === 'video') {
    clearImageLoader()
    isLoaded.value = false
    hasError.value = false
  }
  else {
    clearImageLoader()
    isLoaded.value = false
    hasError.value = false
  }
}, { immediate: true })

onUnmounted(() => {
  clearImageLoader()
})
</script>

<template>
  <div v-if="showBackground" class="background-container" :style="backgroundContainerStyle">
    <Transition name="fade">
      <div v-if="showDefaultBackground" class="background-default" />
    </Transition>
    <Transition name="fade">
      <div v-if="showLoadingBackground" class="background-loading" />
    </Transition>
    <Transition name="fade">
      <div v-if="showMediaBackground" class="background-media" :style="backgroundStyle">
        <div
          v-if="backgroundType === 'image'"
          class="background-image"
          :style="{ backgroundImage: `url(${currentUrl})` }"
        />
        <video
          v-else-if="backgroundType === 'video'"
          ref="videoRef"
          class="background-video"
          :src="currentUrl ?? undefined"
          autoplay
          loop
          muted
          preload="auto"
          playsinline
          @loadeddata="handleVideoLoaded"
          @canplay="handleVideoLoaded"
          @error="handleVideoError"
        />
      </div>
    </Transition>
    <div v-if="showBackgroundOverlay" class="background-overlay" :style="overlayStyle" />
  </div>
</template>

<style scoped>
.background-container {
  position: fixed;
  inset: 0;
  z-index: -1;
  overflow: hidden;
}

.background-default,
.background-loading {
  position: absolute;
  inset: 0;
  background-color: var(--background);
}

.background-media {
  position: absolute;
  inset: 0;
  transform: scale(1.1);
  transition: opacity 0.8s ease;
}

.background-image {
  width: 100%;
  height: 100%;
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;
}

.background-video {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.background-overlay {
  position: absolute;
  inset: 0;
  pointer-events: none;
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.8s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>
