// src/components/node/NodeList.tsx
"use client";

import { Icon } from "@iconify/react";
import { useMemo, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { ProgressThin } from "@/components/ui/ProgressThin";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { NodePingListCell } from "@/components/node/NodePingListCell";
import { TrafficProgress } from "@/components/node/TrafficProgress";
import { useAppStore } from "@/stores/app";
import type { NodeData } from "@/stores/nodes";
import {
  formatBytesPerSecondWithConfig,
  formatBytesWithConfig,
  formatDateTime,
  formatUptimeWithFormat,
  getStatus,
} from "@/utils/helper";
import { getOSImage, getOSName } from "@/utils/osImageHelper";
import { getRegionCode, getRegionDisplayName } from "@/utils/regionHelper";
import {
  formatPriceWithCycle,
  getDaysUntilExpired,
  getExpireStatus,
  getExpireTextClass,
  parseTags,
} from "@/utils/tagHelper";

interface ColumnConfig {
  key: string;
  label: string;
  width: string | number;
  sortable: boolean;
}

interface PriceTagItem {
  text: string;
  highlightValue?: string;
  prefix?: string;
  suffix?: string;
}

interface NodeListProps {
  nodes: NodeData[];
  transitionKey?: string;
  onClick?: (node: NodeData) => void;
  onPingClick?: (node: NodeData) => void;
}

const ROW_STAGGER_MS = 35;
const ROW_STAGGER_LIMIT = 12;

const COLUMNS: ColumnConfig[] = [
  { key: "status", label: "状态", width: "40px", sortable: false },
  { key: "os", label: "系统", width: "40px", sortable: false },
  { key: "name", label: "节点", width: "minmax(160px, 0.8fr)", sortable: true },
  { key: "tags", label: "标签", width: "minmax(200px, 1fr)", sortable: false },
  { key: "uptime", label: "运行时间", width: "116px", sortable: true },
  { key: "cpu", label: "CPU", width: "100px", sortable: false },
  { key: "mem", label: "内存", width: "100px", sortable: false },
  { key: "disk", label: "硬盘", width: "100px", sortable: false },
  { key: "traffic", label: "流量", width: "100px", sortable: false },
  { key: "rate", label: "速率", width: "80px", sortable: true },
];

export function NodeList({ nodes, transitionKey, onClick, onPingClick }: NodeListProps) {
  const byteDecimals = useAppStore((s) => s.byteDecimals);
  const lang = useAppStore((s) => s.lang);

  const [sortKey, setSortKey] = useState<string>("");
  const [sortDir, setSortDir] = useState<1 | -1>(1);

  function handleSort(col: ColumnConfig) {
    if (!col.sortable) return;
    if (sortKey === col.key) setSortDir(sortDir === 1 ? -1 : 1);
    else {
      setSortKey(col.key);
      setSortDir(1);
    }
  }

  const sortedNodes = useMemo(() => {
    const list = [...nodes];
    if (!sortKey) return list;
    const dir = sortDir;
    return list.sort((a, b) => {
      switch (sortKey) {
        case "status":
          return dir * ((a.online ? 1 : 0) - (b.online ? 1 : 0));
        case "name": {
          const va = (a.name || "").toLowerCase();
          const vb = (b.name || "").toLowerCase();
          return dir * (va < vb ? -1 : va > vb ? 1 : 0);
        }
        case "uptime":
          return dir * ((a.uptime ?? 0) - (b.uptime ?? 0));
        case "cpu":
          return dir * ((a.cpu ?? 0) - (b.cpu ?? 0));
        case "mem":
          return dir * (
            (a.ram ?? 0) / (a.mem_total || 1) - (b.ram ?? 0) / (b.mem_total || 1)
          );
        case "disk":
          return dir * (
            (a.disk ?? 0) / (a.disk_total || 1) - (b.disk ?? 0) / (b.disk_total || 1)
          );
        case "traffic":
        case "rate":
          return dir * (((a.net_out ?? 0) + (a.net_in ?? 0)) - ((b.net_out ?? 0) + (b.net_in ?? 0)));
        default:
          return 0;
      }
    });
  }, [nodes, sortKey, sortDir]);

  const formatBytes = (bytes: number) => formatBytesWithConfig(bytes, byteDecimals);
  const formatBytesPerSecond = (bytes: number) =>
    formatBytesPerSecondWithConfig(bytes, byteDecimals);
  const formatUptime = (seconds: number) => formatUptimeWithFormat(seconds, "hour");

  const gridStyle = useMemo(
    () => ({
      gridTemplateColumns: COLUMNS.map((c) => c.width).join(" "),
    }),
    [],
  );

  function getFlagSrc(region: string): string {
    return `/images/flags/${getRegionCode(region)}.svg`;
  }
  function hasRegion(region: string | null | undefined): boolean {
    return Boolean(region?.trim());
  }
  function getRowTransitionKey(node: NodeData): string {
    return transitionKey ? `${transitionKey}-${node.uuid}` : node.uuid;
  }
  function getRowTransitionStyle(index: number): React.CSSProperties {
    return { ["--node-row-delay" as string]: `${Math.min(index, ROW_STAGGER_LIMIT) * ROW_STAGGER_MS}ms` };
  }
  function showTrafficProgress(node: NodeData): boolean {
    return node.traffic_limit > 0;
  }
  function getTrafficUsed(node: NodeData): number {
    const up = node.net_total_up ?? 0;
    const down = node.net_total_down ?? 0;
    switch (node.traffic_limit_type) {
      case "up":
        return up;
      case "down":
        return down;
      case "min":
        return Math.min(up, down);
      case "max":
        return Math.max(up, down);
      case "sum":
      default:
        return up + down;
    }
  }
  function getTrafficUsedPercentage(node: NodeData): number {
    if (node.traffic_limit <= 0) return 0;
    return Math.min((getTrafficUsed(node) / node.traffic_limit) * 100, 100);
  }
  function formatOfflineTime(node: NodeData): string {
    return formatDateTime(node.time);
  }
  function getPriceTags(node: NodeData): PriceTagItem[] {
    const tags: PriceTagItem[] = [];
    if (node.price !== 0) {
      const days = getDaysUntilExpired(node.expired_at);
      const status = getExpireStatus(node.expired_at);
      tags.push({ text: formatPriceWithCycle(node.price, node.billing_cycle, node.currency, lang) });
      if (status === "expired") tags.push({ text: lang === "zh-CN" ? "已过期" : "Expired" });
      else if (status === "long_term") tags.push({ text: lang === "zh-CN" ? "长期" : "Long-term" });
      else if (lang === "zh-CN")
        tags.push({ text: `剩余 ${days} 天`, prefix: "剩余 ", highlightValue: String(days), suffix: " 天" });
      else
        tags.push({ text: `${days} days left`, highlightValue: String(days), suffix: " days left" });
    }
    return tags;
  }

  return (
    <div className="overflow-x-auto">
      <div className="min-w-[920px] text-xs">
        <div className="gap-2 grid items-center pb-2 border-b border-border text-muted-foreground" style={gridStyle}>
          {COLUMNS.map((col) => (
            <button
              key={col.key}
              type="button"
              onClick={() => handleSort(col)}
              className={`text-left px-2 ${col.sortable ? "cursor-pointer hover:text-foreground" : "cursor-default"}`}
            >
              {col.label}
              {sortKey === col.key && (
                <Icon
                  icon={sortDir === 1 ? "tabler:arrow-up" : "tabler:arrow-down"}
                  className="inline ml-1"
                  width={12}
                  height={12}
                />
              )}
            </button>
          ))}
        </div>

        <div>
          {sortedNodes.map((node, index) => {
            const cpuStatus = getStatus(node.cpu ?? 0);
            const memPercentage = ((node.ram ?? 0) / (node.mem_total || 1)) * 100;
            const memStatus = getStatus(memPercentage);
            const diskPercentage = ((node.disk ?? 0) / (node.disk_total || 1)) * 100;
            const diskStatus = getStatus(diskPercentage);
            const customTags = parseTags(node.tags).map((t) => t.text);
            const priceTags = getPriceTags(node);
            const remainingTimeTagClass =
              node.price === 0 ? "" : getExpireTextClass(node.expired_at);

            return (
              <div
                key={getRowTransitionKey(node)}
                className="gap-2 grid items-center py-2 border-b border-border/50 hover:bg-muted/30 cursor-pointer transition-colors"
                style={gridStyle}
                onClick={() => onClick?.(node)}
              >
                <div className="px-2 relative size-2">
                  <span
                    className={`block size-2 rounded-full ${node.online ? "bg-green-600" : "bg-red-600"}`}
                  />
                  {node.online && (
                    <span className="absolute inset-0 rounded-full bg-green-600 opacity-50 animate-ping" />
                  )}
                </div>
                <div className="px-2">
                  <img src={getOSImage(node.os)} alt={getOSName(node.os)} className="size-4" />
                </div>
                <div className="px-2 min-w-0 flex items-center gap-2">
                  {hasRegion(node.region) && (
                    <img src={getFlagSrc(node.region!)} alt={getRegionDisplayName(node.region!)} className="size-4 shrink-0" />
                  )}
                  <span className="truncate font-medium">{node.name}</span>
                </div>
                <div className="px-2 flex flex-wrap gap-1">
                  {customTags.length > 0 ? (
                    customTags.map((tag, i) => (
                      <Badge key={i} variant="outline" className="!text-[10px] rounded text-muted-foreground border-muted-foreground/10 px-1.5">
                        {tag}
                      </Badge>
                    ))
                  ) : (
                    <span className="text-muted-foreground">-</span>
                  )}
                </div>
                <div className="px-2 text-muted-foreground truncate">{formatUptime(node.uptime ?? 0)}</div>
                <div className="px-2 space-y-1">
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">CPU</span>
                    <span>{(node.cpu ?? 0).toFixed(1)}%</span>
                  </div>
                  <ProgressThin percentage={node.cpu ?? 0} status={cpuStatus} height={3} />
                </div>
                <div className="px-2 space-y-1">
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">MEM</span>
                    <span>{memPercentage.toFixed(1)}%</span>
                  </div>
                  <ProgressThin percentage={memPercentage} status={memStatus} height={3} />
                </div>
                <div className="px-2 space-y-1">
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">DISK</span>
                    <span>{diskPercentage.toFixed(1)}%</span>
                  </div>
                  <ProgressThin percentage={diskPercentage} status={diskStatus} height={3} />
                </div>
                <div className="px-2 space-y-1">
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">流量</span>
                    <span>{getTrafficUsedPercentage(node).toFixed(1)}%</span>
                  </div>
                  {showTrafficProgress(node) ? (
                    <TrafficProgress
                      upload={node.net_total_up ?? 0}
                      download={node.net_total_down ?? 0}
                      trafficLimit={node.traffic_limit}
                      trafficLimitType={node.traffic_limit_type}
                      height={3}
                    />
                  ) : (
                    <span className="text-muted-foreground">∞</span>
                  )}
                </div>
                <div
                  className="px-2 text-right text-muted-foreground truncate"
                  onClick={(e) => {
                    e.stopPropagation();
                    onPingClick?.(node);
                  }}
                  role="button"
                  tabIndex={0}
                  onKeyDown={(e) => {
                    if (e.key === "Enter" || e.key === " ") {
                      e.preventDefault();
                      onPingClick?.(node);
                    }
                  }}
                >
                  <NodePingListCell uuid={node.uuid} online={node.online} />
                </div>

                {!node.online && (
                  <div
                    className="px-2 col-span-full flex flex-row items-center gap-2 text-destructive text-xs"
                    style={getRowTransitionStyle(index)}
                  >
                    <span className="font-medium">离线</span>
                    <span className="text-muted-foreground">{formatOfflineTime(node)}</span>
                  </div>
                )}

                {priceTags.length > 0 && (
                  <div className="px-2 col-span-full text-[10px] text-muted-foreground flex flex-wrap gap-3">
                    {priceTags.map((tag, i) => (
                      <span key={i} className="flex items-center gap-1">
                        {tag.highlightValue ? (
                          <>
                            <span>{tag.prefix}</span>
                            <span className={remainingTimeTagClass}>{tag.highlightValue}</span>
                            <span>{tag.suffix}</span>
                          </>
                        ) : (
                          <span>{tag.text}</span>
                        )}
                      </span>
                    ))}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}

export default NodeList;

// src/components/NodeList.vue
<script setup lang="ts">
import type { NodeData } from '@/stores/nodes'
import { Icon } from '@iconify/vue'
import { computed, ref } from 'vue'
import NodePingListCell from '@/components/NodePingListCell.vue'
import TrafficProgress from '@/components/TrafficProgress.vue'
import { Badge } from '@/components/ui/badge'
import { ProgressThin } from '@/components/ui/progress-thin'
import { useAppStore } from '@/stores/app'
import { formatBytesPerSecondWithConfig, formatBytesWithConfig, formatDateTime, formatUptimeWithFormat, getStatus } from '@/utils/helper'
import { getOSImage, getOSName } from '@/utils/osImageHelper'
import { getRegionCode, getRegionDisplayName } from '@/utils/regionHelper'
import { formatPriceWithCycle, getDaysUntilExpired, getExpireStatus, parseTags } from '@/utils/tagHelper'

interface ColumnConfig {
  key: string
  label: string
  width: string | number
  sortable: boolean
}

const props = defineProps<{ nodes: NodeData[] }>()

const emit = defineEmits<{ click: [node: NodeData] }>()

const appStore = useAppStore()

const columns: ColumnConfig[] = [
  { key: 'status', label: '状态', width: '40px', sortable: false },
  { key: 'os', label: '系统', width: '40px', sortable: false },
  { key: 'name', label: '节点', width: 'minmax(160px, 0.8fr)', sortable: true },
  { key: 'tags', label: '标签', width: 'minmax(200px, 1fr)', sortable: false },
  { key: 'uptime', label: '运行时间', width: '116px', sortable: true },
  { key: 'cpu', label: 'CPU', width: '100px', sortable: false },
  { key: 'mem', label: '内存', width: '100px', sortable: false },
  { key: 'disk', label: '硬盘', width: '100px', sortable: false },
  { key: 'traffic', label: '流量', width: '100px', sortable: false },
  { key: 'rate', label: '速率', width: '80px', sortable: true },
]

const sortKey = ref<string>('')
const sortDir = ref<1 | -1>(1)

function handleSort(col: ColumnConfig) {
  if (!col.sortable)
    return
  if (sortKey.value === col.key) {
    sortDir.value = sortDir.value === 1 ? -1 : 1
  }
  else {
    sortKey.value = col.key
    sortDir.value = 1
  }
}

const sortedNodes = computed(() => {
  const nodes = [...props.nodes]
  const key = sortKey.value
  const dir = sortDir.value
  if (!key)
    return nodes
  return nodes.sort((a, b) => {
    switch (key) {
      case 'status': return dir * ((a.online ? 1 : 0) - (b.online ? 1 : 0))
      case 'region': {
        const va = (a.region || '').toLowerCase()
        const vb = (b.region || '').toLowerCase()
        return dir * (va < vb ? -1 : va > vb ? 1 : 0)
      }
      case 'name': {
        const va = (a.name || '').toLowerCase()
        const vb = (b.name || '').toLowerCase()
        return dir * (va < vb ? -1 : va > vb ? 1 : 0)
      }
      case 'uptime': return dir * ((a.uptime ?? 0) - (b.uptime ?? 0))
      case 'os': {
        const va = (a.os || '').toLowerCase()
        const vb = (b.os || '').toLowerCase()
        return dir * (va < vb ? -1 : va > vb ? 1 : 0)
      }
      case 'cpu': return dir * ((a.cpu ?? 0) - (b.cpu ?? 0))
      case 'mem': return dir * ((a.ram ?? 0) / (a.mem_total || 1) - (b.ram ?? 0) / (b.mem_total || 1))
      case 'disk': return dir * ((a.disk ?? 0) / (a.disk_total || 1) - (b.disk ?? 0) / (b.disk_total || 1))
      case 'traffic':
      case 'rate':
        return dir * (((a.net_out ?? 0) + (a.net_in ?? 0)) - ((b.net_out ?? 0) + (b.net_in ?? 0)))
      default: return 0
    }
  })
})

const formatBytes = (bytes: number) => formatBytesWithConfig(bytes)
const formatBytesPerSecond = (bytes: number) => formatBytesPerSecondWithConfig(bytes)
const formatUptime = (seconds: number) => formatUptimeWithFormat(seconds, 'hour')

const columnKeys = computed(() => columns.map(c => c.key))

const gridStyle = computed(() => ({
  gridTemplateColumns: columns.map(c => c.width).join(' '),
}))

const offlineOverlayContentStyle = computed(() => {
  const keys = columnKeys.value
  const statusIndex = keys.indexOf('status')
  const regionIndex = keys.indexOf('region')
  const nameIndex = keys.indexOf('name')
  const startColumn = nameIndex !== -1
    ? nameIndex + 1
    : regionIndex !== -1
      ? regionIndex + 2
      : statusIndex === -1 ? 1 : statusIndex + 2
  return { gridColumn: `${startColumn} / -1` }
})

function getFlagSrc(region: string): string {
  return `/images/flags/${getRegionCode(region)}.svg`
}

function hasRegion(region: string | null | undefined): boolean {
  return Boolean(region?.trim())
}

function handleClick(node: NodeData) {
  emit('click', node)
}

function showTrafficProgress(node: NodeData): boolean {
  return node.traffic_limit > 0
}

function getTrafficUsedPercentage(node: NodeData): number {
  if (node.traffic_limit <= 0)
    return 0
  const { net_total_up = 0, net_total_down = 0, traffic_limit_type } = node
  let used = 0
  switch (traffic_limit_type) {
    case 'up': used = net_total_up
      break
    case 'down': used = net_total_down
      break
    case 'min': used = Math.min(net_total_up, net_total_down)
      break
    case 'max': used = Math.max(net_total_up, net_total_down)
      break
    case 'sum':
    default:
      used = net_total_up + net_total_down
      break
  }
  return Math.min((used / node.traffic_limit) * 100, 100)
}

function getTrafficUsed(node: NodeData): number {
  const { net_total_up = 0, net_total_down = 0, traffic_limit_type } = node
  switch (traffic_limit_type) {
    case 'up': return net_total_up
    case 'down': return net_total_down
    case 'min': return Math.min(net_total_up, net_total_down)
    case 'max': return Math.max(net_total_up, net_total_down)
    case 'sum':
    default: return net_total_up + net_total_down
  }
}

function formatOfflineTime(node: NodeData): string {
  return formatDateTime(node.time)
}

function getPriceTags(node: NodeData): Array<string> {
  const tags: Array<string> = []
  const lang = appStore.lang
  if (node.price !== 0) {
    const days = getDaysUntilExpired(node.expired_at)
    const status = getExpireStatus(node.expired_at)
    if (status === 'expired')
      tags.push(lang === 'zh-CN' ? '已过期' : 'Expired')
    else if (status === 'long_term')
      tags.push(lang === 'zh-CN' ? '长期' : 'Long-term')
    else tags.push(lang === 'zh-CN' ? `剩余 ${days} 天` : `${days} days left`)
    const priceText = formatPriceWithCycle(node.price, node.billing_cycle, node.currency, lang)
    tags.push(priceText)
  }
  return tags
}

function getCustomTags(node: NodeData): Array<string> {
  return parseTags(node.tags).map(t => t.text)
}
</script>

<template>
  <div class="overflow-x-auto min-w-0">
    <div class="min-w-fit w-full flex flex-col gap-1">
      <!-- 表头 -->
      <div class="grid p-2 bg-background/60 rounded-lg backdrop-blur-sm gap-2" :style="gridStyle">
        <div
          v-for="col in columns" :key="col.key"
          :class="[col.sortable ? 'cursor-pointer' : '', ['status', 'os'].includes(col.key) ? 'text-center' : 'text-left']"
          @click="handleSort(col)"
        >
          <span class="text-xs text-muted-foreground">
            {{ col.label }}{{ col.sortable && sortKey === col.key ? (sortDir === 1 ? ' ↑' : ' ↓') : '' }}
          </span>
        </div>
      </div>

      <!-- 行 -->
      <div
        v-for="node in sortedNodes" :key="node.uuid"
        class="flex flex-col relative h-16 justify-center px-2 cursor-pointer bg-background/30 rounded-lg backdrop-blur-sm inset-shadow-[0_0_0_2px] inset-shadow-transparent hover:inset-shadow-green-600/20 hover:bg-background transition-all"
        :class="[!node.online && '!inset-shadow-red-600/10']" @click="handleClick(node)"
      >
        <div class="grid gap-2 items-center" :style="gridStyle">
          <template v-for="col in columns" :key="col.key">
            <!-- 在线状态指示器 -->
            <div v-if="col.key === 'status'" class="flex justify-center">
              <div class="size-2 rounded-full relative" :class="[node.online ? 'bg-green-600' : 'bg-red-600']">
                <div
                  class="animate-ping absolute inset-0 rounded-full opacity-50"
                  :class="[node.online ? 'bg-green-600' : 'bg-red-600']"
                />
              </div>
            </div>

            <!-- 节点名称 -->
            <div v-else-if="col.key === 'name'" class="space-y-0.5" :class="[!node.online && 'blur-sm opacity-30']">
              <div class="flex gap-1 items-center text-xs font-semibold">
                <img
                  v-if="hasRegion(node.region)" :src="getFlagSrc(node.region)"
                  :alt="getRegionDisplayName(node.region)" class="size-5 rounded-sm"
                >
                <span class="truncate">{{ node.name }}</span>
              </div>
              <div
                v-if="getPriceTags(node).length > 0"
                class="text-[11px] text-muted-foreground/70 truncate"
              >
                <span v-for="(tag, index) in getPriceTags(node)" :key="index" :class="!!index && 'ml-3'">
                  {{ tag }}
                </span>
              </div>
            </div>

            <!-- 标签 -->
            <div v-else-if="col.key === 'tags'">
              <div class="flex flex-wrap gap-1 items-center">
                <Badge
                  v-for="(tag, index) in getCustomTags(node)" :key="index" variant="outline"
                  class="!text-[11px] rounded text-muted-foreground border-muted-foreground/10 px-1.5"
                >
                  {{ tag }}
                </Badge>
              </div>
            </div>

            <!-- 延迟/丢包 -->
            <!-- <div v-else-if="col.key === 'ping'">
              <NodePingListCell :uuid="node.uuid" :online="node.online" />
            </div> -->

            <!-- 运行时间 -->
            <div v-else-if="col.key === 'uptime'" class="flex flex-col gap-0.5">
              <span class="text-[10px] text-muted-foreground truncate">
                {{ formatUptime(node.uptime ?? 0) }}
              </span>
              <NodePingListCell :uuid="node.uuid" :online="node.online" />
            </div>

            <!-- 操作系统 -->
            <div v-else-if="col.key === 'os'" class="flex justify-center">
              <img :src="getOSImage(node.os)" :alt="getOSName(node.os)" class="size-4">
            </div>

            <!-- CPU -->
            <div v-else-if="col.key === 'cpu'" class="group">
              <div class="space-y-1">
                <div class="text-[10px] text-muted-foreground truncate">
                  <span class="inline group-hover:hidden">
                    {{ (node.cpu ?? 0).toFixed(1) }}%
                  </span>
                  <span class="hidden group-hover:inline">
                    {{ node.load.toFixed(2) ?? 0 }}, {{ node.load5.toFixed(2) ?? 0 }}, {{ node.load15.toFixed(2) ?? 0
                    }}
                  </span>
                </div>
                <ProgressThin :percentage="node.cpu ?? 0" :status="getStatus(node.cpu ?? 0)" :height="4" />
              </div>
            </div>

            <!-- 内存 -->
            <div v-else-if="col.key === 'mem'" class="group">
              <div class="space-y-1">
                <div class="text-[10px] text-muted-foreground truncate">
                  <span class="inline group-hover:hidden">
                    {{ ((node.ram ?? 0) / (node.mem_total || 1) * 100).toFixed(1) }}%
                  </span>
                  <span class="hidden group-hover:inline">
                    {{ formatBytes(node.ram ?? 0) }} / {{ formatBytes(node.mem_total ?? 0) }}
                  </span>
                </div>
                <ProgressThin
                  :percentage="(node.ram ?? 0) / (node.mem_total || 1) * 100"
                  :status="getStatus((node.ram ?? 0) / (node.mem_total || 1) * 100)" :height="4"
                />
              </div>
            </div>

            <!-- 硬盘 -->
            <div v-else-if="col.key === 'disk'" class="group">
              <div class="space-y-1">
                <div class="text-[10px] text-muted-foreground truncate">
                  <span class="inline group-hover:hidden">
                    {{ ((node.disk ?? 0) / (node.disk_total || 1) * 100).toFixed(1) }}%
                  </span>
                  <span class="hidden group-hover:inline">
                    {{ formatBytes(node.disk ?? 0) }} / {{ formatBytes(node.disk_total ?? 0) }}
                  </span>
                </div>
                <ProgressThin
                  :percentage="(node.disk ?? 0) / (node.disk_total || 1) * 100"
                  :status="getStatus((node.disk ?? 0) / (node.disk_total || 1) * 100)" :height="4"
                />
              </div>
            </div>

            <!-- 流量 -->
            <div v-else-if="col.key === 'traffic'" class="group">
              <div class="group/traffic relative flex items-center gap-2">
                <div class="space-y-1 w-full">
                  <div class="text-[10px] text-muted-foreground truncate">
                    <span class="inline group-hover:hidden">
                      {{ getTrafficUsedPercentage(node).toFixed(1) }}%
                    </span>
                    <span class="hidden group-hover:inline">
                      {{ formatBytes(getTrafficUsed(node)) }} /
                      <template v-if="showTrafficProgress(node)">{{ formatBytes(node.traffic_limit) }}</template>
                      <template v-else>∞</template>
                    </span>
                  </div>
                  <TrafficProgress
                    :upload="node.net_total_up ?? 0" :download="node.net_total_down ?? 0"
                    :traffic-limit="node.traffic_limit" :traffic-limit-type="(node.traffic_limit_type || 'sum')"
                    height="4px"
                  />
                </div>
                <div
                  class="pointer-events-none absolute bottom-full left-1/2 z-20 hidden mb-1.5 -translate-x-1/2 whitespace-nowrap rounded bg-foreground/80 p-1 text-[10px] leading-none text-background shadow-lg group-hover/traffic:block"
                >
                  <span class="flex flex-row gap-0.5 items-center">
                    <Icon icon="tabler:chevron-up" width="12" height="12" />
                    {{ formatBytes(node.net_total_up ?? 0) }}
                  </span>
                  <span class="flex flex-row gap-0.5 items-center">
                    <Icon icon="tabler:chevron-down" width="12" height="12" />
                    {{ formatBytes(node.net_total_down ?? 0) }}
                  </span>
                </div>
              </div>
            </div>

            <!-- 速率 -->
            <div v-else-if="col.key === 'rate'">
              <div class="text-[10px] flex flex-col ">
                <span class="text-green-600 flex flex-row gap-1 items-center">
                  <Icon icon="tabler:chevron-up" width="12" height="12" />
                  {{ formatBytesPerSecond(node.net_out ?? 0) }}
                </span>
                <span class="text-blue-600 flex flex-row gap-1 items-center">
                  <Icon icon="tabler:chevron-down" width="12" height="12" />
                  {{ formatBytesPerSecond(node.net_in ?? 0) }}
                </span>
              </div>
            </div>
          </template>
        </div>

        <div
          v-if="!node.online" class="absolute inset-0 z-2 p-2 bg-background/10 rounded-lg flex items-center"
          aria-hidden="true"
        >
          <div class="grid gap-2 items-center justify-center" :style="gridStyle">
            <div class="h-full space-y-1" :style="offlineOverlayContentStyle">
              <div class="text-sm font-semibold truncate">
                <span class="text-red-500">离线</span> {{ node.name }}
              </div>
              <div class="text-xs text-muted-foreground">
                {{ formatOfflineTime(node) }}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
