// src/components/NodeList.vue
<script setup lang="ts">
import type { NodeData } from '@/stores/nodes'
import { Icon } from '@iconify/vue'
import { computed, ref } from 'vue'
import NodePingListCell from '@/components/NodePingListCell.vue'
import TrafficProgress from '@/components/TrafficProgress.vue'
import { Badge } from '@/components/ui/badge'
import { ProgressThin } from '@/components/ui/progress-thin'
import { useAppStore } from '@/stores/app'
import { formatBytesPerSecondWithConfig, formatBytesWithConfig, formatDateTime, formatUptimeWithFormat, getStatus } from '@/utils/helper'
import { getOSImage, getOSName } from '@/utils/osImageHelper'
import { getRegionCode, getRegionDisplayName } from '@/utils/regionHelper'
import { formatPriceWithCycle, getDaysUntilExpired, getExpireStatus, parseTags } from '@/utils/tagHelper'

interface ColumnConfig {
  key: string
  label: string
  width: string | number
  sortable: boolean
}

const props = defineProps<{ nodes: NodeData[] }>()

const emit = defineEmits<{ click: [node: NodeData] }>()

const appStore = useAppStore()

const columns: ColumnConfig[] = [
  { key: 'status', label: '状态', width: '40px', sortable: false },
  { key: 'os', label: '系统', width: '40px', sortable: false },
  { key: 'name', label: '节点', width: 'minmax(160px, 0.8fr)', sortable: true },
  { key: 'tags', label: '标签', width: 'minmax(200px, 1fr)', sortable: false },
  { key: 'uptime', label: '运行时间', width: '116px', sortable: true },
  { key: 'cpu', label: 'CPU', width: '100px', sortable: false },
  { key: 'mem', label: '内存', width: '100px', sortable: false },
  { key: 'disk', label: '硬盘', width: '100px', sortable: false },
  { key: 'traffic', label: '流量', width: '100px', sortable: false },
  { key: 'rate', label: '速率', width: '80px', sortable: true },
]

const sortKey = ref<string>('')
const sortDir = ref<1 | -1>(1)

function handleSort(col: ColumnConfig) {
  if (!col.sortable)
    return
  if (sortKey.value === col.key) {
    sortDir.value = sortDir.value === 1 ? -1 : 1
  }
  else {
    sortKey.value = col.key
    sortDir.value = 1
  }
}

const sortedNodes = computed(() => {
  const nodes = [...props.nodes]
  const key = sortKey.value
  const dir = sortDir.value
  if (!key)
    return nodes
  return nodes.sort((a, b) => {
    switch (key) {
      case 'status': return dir * ((a.online ? 1 : 0) - (b.online ? 1 : 0))
      case 'region': {
        const va = (a.region || '').toLowerCase()
        const vb = (b.region || '').toLowerCase()
        return dir * (va < vb ? -1 : va > vb ? 1 : 0)
      }
      case 'name': {
        const va = (a.name || '').toLowerCase()
        const vb = (b.name || '').toLowerCase()
        return dir * (va < vb ? -1 : va > vb ? 1 : 0)
      }
      case 'uptime': return dir * ((a.uptime ?? 0) - (b.uptime ?? 0))
      case 'os': {
        const va = (a.os || '').toLowerCase()
        const vb = (b.os || '').toLowerCase()
        return dir * (va < vb ? -1 : va > vb ? 1 : 0)
      }
      case 'cpu': return dir * ((a.cpu ?? 0) - (b.cpu ?? 0))
      case 'mem': return dir * ((a.ram ?? 0) / (a.mem_total || 1) - (b.ram ?? 0) / (b.mem_total || 1))
      case 'disk': return dir * ((a.disk ?? 0) / (a.disk_total || 1) - (b.disk ?? 0) / (b.disk_total || 1))
      case 'traffic':
      case 'rate':
        return dir * (((a.net_out ?? 0) + (a.net_in ?? 0)) - ((b.net_out ?? 0) + (b.net_in ?? 0)))
      default: return 0
    }
  })
})

const formatBytes = (bytes: number) => formatBytesWithConfig(bytes)
const formatBytesPerSecond = (bytes: number) => formatBytesPerSecondWithConfig(bytes)
const formatUptime = (seconds: number) => formatUptimeWithFormat(seconds, 'hour')

const columnKeys = computed(() => columns.map(c => c.key))

const gridStyle = computed(() => ({
  gridTemplateColumns: columns.map(c => c.width).join(' '),
}))

const offlineOverlayContentStyle = computed(() => {
  const keys = columnKeys.value
  const statusIndex = keys.indexOf('status')
  const regionIndex = keys.indexOf('region')
  const nameIndex = keys.indexOf('name')
  const startColumn = nameIndex !== -1
    ? nameIndex + 1
    : regionIndex !== -1
      ? regionIndex + 2
      : statusIndex === -1 ? 1 : statusIndex + 2
  return { gridColumn: `${startColumn} / -1` }
})

function getFlagSrc(region: string): string {
  return `/images/flags/${getRegionCode(region)}.svg`
}

function hasRegion(region: string | null | undefined): boolean {
  return Boolean(region?.trim())
}

function handleClick(node: NodeData) {
  emit('click', node)
}

function showTrafficProgress(node: NodeData): boolean {
  return node.traffic_limit > 0
}

function getTrafficUsedPercentage(node: NodeData): number {
  if (node.traffic_limit <= 0)
    return 0
  const { net_total_up = 0, net_total_down = 0, traffic_limit_type } = node
  let used = 0
  switch (traffic_limit_type) {
    case 'up': used = net_total_up
      break
    case 'down': used = net_total_down
      break
    case 'min': used = Math.min(net_total_up, net_total_down)
      break
    case 'max': used = Math.max(net_total_up, net_total_down)
      break
    case 'sum':
    default:
      used = net_total_up + net_total_down
      break
  }
  return Math.min((used / node.traffic_limit) * 100, 100)
}

function getTrafficUsed(node: NodeData): number {
  const { net_total_up = 0, net_total_down = 0, traffic_limit_type } = node
  switch (traffic_limit_type) {
    case 'up': return net_total_up
    case 'down': return net_total_down
    case 'min': return Math.min(net_total_up, net_total_down)
    case 'max': return Math.max(net_total_up, net_total_down)
    case 'sum':
    default: return net_total_up + net_total_down
  }
}

function formatOfflineTime(node: NodeData): string {
  return formatDateTime(node.time)
}

function getPriceTags(node: NodeData): Array<string> {
  const tags: Array<string> = []
  const lang = appStore.lang
  if (node.price !== 0) {
    const days = getDaysUntilExpired(node.expired_at)
    const status = getExpireStatus(node.expired_at)
    if (status === 'expired')
      tags.push(lang === 'zh-CN' ? '已过期' : 'Expired')
    else if (status === 'long_term')
      tags.push(lang === 'zh-CN' ? '长期' : 'Long-term')
    else tags.push(lang === 'zh-CN' ? `剩余 ${days} 天` : `${days} days left`)
    const priceText = formatPriceWithCycle(node.price, node.billing_cycle, node.currency, lang)
    tags.push(priceText)
  }
  return tags
}

function getCustomTags(node: NodeData): Array<string> {
  return parseTags(node.tags).map(t => t.text)
}
</script>

<template>
  <div class="overflow-x-auto min-w-0">
    <div class="min-w-fit w-full flex flex-col gap-1">
      <!-- 表头 -->
      <div class="grid p-2 bg-background/60 rounded-lg backdrop-blur-sm gap-2" :style="gridStyle">
        <div
          v-for="col in columns" :key="col.key"
          :class="[col.sortable ? 'cursor-pointer' : '', ['status', 'os'].includes(col.key) ? 'text-center' : 'text-left']"
          @click="handleSort(col)"
        >
          <span class="text-xs text-muted-foreground">
            {{ col.label }}{{ col.sortable && sortKey === col.key ? (sortDir === 1 ? ' ↑' : ' ↓') : '' }}
          </span>
        </div>
      </div>

      <!-- 行 -->
      <div
        v-for="node in sortedNodes" :key="node.uuid"
        class="flex flex-col relative h-16 justify-center px-2 cursor-pointer bg-background/30 rounded-lg backdrop-blur-sm inset-shadow-[0_0_0_2px] inset-shadow-transparent hover:inset-shadow-green-600/20 hover:bg-background transition-all"
        :class="[!node.online && '!inset-shadow-red-600/10']" @click="handleClick(node)"
      >
        <div class="grid gap-2 items-center" :style="gridStyle">
          <template v-for="col in columns" :key="col.key">
            <!-- 在线状态指示器 -->
            <div v-if="col.key === 'status'" class="flex justify-center">
              <div class="size-2 rounded-full relative" :class="[node.online ? 'bg-green-600' : 'bg-red-600']">
                <div
                  class="animate-ping absolute inset-0 rounded-full opacity-50"
                  :class="[node.online ? 'bg-green-600' : 'bg-red-600']"
                />
              </div>
            </div>

            <!-- 节点名称 -->
            <div v-else-if="col.key === 'name'" class="space-y-0.5" :class="[!node.online && 'blur-sm opacity-30']">
              <div class="flex gap-1 items-center text-xs font-semibold">
                <img
                  v-if="hasRegion(node.region)" :src="getFlagSrc(node.region)"
                  :alt="getRegionDisplayName(node.region)" class="size-5 rounded-sm"
                >
                <span class="truncate">{{ node.name }}</span>
              </div>
              <div
                v-if="getPriceTags(node).length > 0"
                class="text-[11px] text-muted-foreground/70 truncate"
              >
                <span v-for="(tag, index) in getPriceTags(node)" :key="index" :class="!!index && 'ml-3'">
                  {{ tag }}
                </span>
              </div>
            </div>

            <!-- 标签 -->
            <div v-else-if="col.key === 'tags'">
              <div class="flex flex-wrap gap-1 items-center">
                <Badge
                  v-for="(tag, index) in getCustomTags(node)" :key="index" variant="outline"
                  class="!text-[11px] rounded text-muted-foreground border-muted-foreground/10 px-1.5"
                >
                  {{ tag }}
                </Badge>
              </div>
            </div>

            <!-- 延迟/丢包 -->
            <!-- <div v-else-if="col.key === 'ping'">
              <NodePingListCell :uuid="node.uuid" :online="node.online" />
            </div> -->

            <!-- 运行时间 -->
            <div v-else-if="col.key === 'uptime'" class="flex flex-col gap-0.5">
              <span class="text-[10px] text-muted-foreground truncate">
                {{ formatUptime(node.uptime ?? 0) }}
              </span>
              <NodePingListCell :uuid="node.uuid" :online="node.online" />
            </div>

            <!-- 操作系统 -->
            <div v-else-if="col.key === 'os'" class="flex justify-center">
              <img :src="getOSImage(node.os)" :alt="getOSName(node.os)" class="size-4">
            </div>

            <!-- CPU -->
            <div v-else-if="col.key === 'cpu'" class="group">
              <div class="space-y-1">
                <div class="text-[10px] text-muted-foreground truncate">
                  <span class="inline group-hover:hidden">
                    {{ (node.cpu ?? 0).toFixed(1) }}%
                  </span>
                  <span class="hidden group-hover:inline">
                    {{ node.load.toFixed(2) ?? 0 }}, {{ node.load5.toFixed(2) ?? 0 }}, {{ node.load15.toFixed(2) ?? 0
                    }}
                  </span>
                </div>
                <ProgressThin :percentage="node.cpu ?? 0" :status="getStatus(node.cpu ?? 0)" :height="4" />
              </div>
            </div>

            <!-- 内存 -->
            <div v-else-if="col.key === 'mem'" class="group">
              <div class="space-y-1">
                <div class="text-[10px] text-muted-foreground truncate">
                  <span class="inline group-hover:hidden">
                    {{ ((node.ram ?? 0) / (node.mem_total || 1) * 100).toFixed(1) }}%
                  </span>
                  <span class="hidden group-hover:inline">
                    {{ formatBytes(node.ram ?? 0) }} / {{ formatBytes(node.mem_total ?? 0) }}
                  </span>
                </div>
                <ProgressThin
                  :percentage="(node.ram ?? 0) / (node.mem_total || 1) * 100"
                  :status="getStatus((node.ram ?? 0) / (node.mem_total || 1) * 100)" :height="4"
                />
              </div>
            </div>

            <!-- 硬盘 -->
            <div v-else-if="col.key === 'disk'" class="group">
              <div class="space-y-1">
                <div class="text-[10px] text-muted-foreground truncate">
                  <span class="inline group-hover:hidden">
                    {{ ((node.disk ?? 0) / (node.disk_total || 1) * 100).toFixed(1) }}%
                  </span>
                  <span class="hidden group-hover:inline">
                    {{ formatBytes(node.disk ?? 0) }} / {{ formatBytes(node.disk_total ?? 0) }}
                  </span>
                </div>
                <ProgressThin
                  :percentage="(node.disk ?? 0) / (node.disk_total || 1) * 100"
                  :status="getStatus((node.disk ?? 0) / (node.disk_total || 1) * 100)" :height="4"
                />
              </div>
            </div>

            <!-- 流量 -->
            <div v-else-if="col.key === 'traffic'" class="group">
              <div class="group/traffic relative flex items-center gap-2">
                <div class="space-y-1 w-full">
                  <div class="text-[10px] text-muted-foreground truncate">
                    <span class="inline group-hover:hidden">
                      {{ getTrafficUsedPercentage(node).toFixed(1) }}%
                    </span>
                    <span class="hidden group-hover:inline">
                      {{ formatBytes(getTrafficUsed(node)) }} /
                      <template v-if="showTrafficProgress(node)">{{ formatBytes(node.traffic_limit) }}</template>
                      <template v-else>∞</template>
                    </span>
                  </div>
                  <TrafficProgress
                    :upload="node.net_total_up ?? 0" :download="node.net_total_down ?? 0"
                    :traffic-limit="node.traffic_limit" :traffic-limit-type="(node.traffic_limit_type || 'sum')"
                    height="4px"
                  />
                </div>
                <div
                  class="pointer-events-none absolute bottom-full left-1/2 z-20 hidden mb-1.5 -translate-x-1/2 whitespace-nowrap rounded bg-foreground/80 p-1 text-[10px] leading-none text-background shadow-lg group-hover/traffic:block"
                >
                  <span class="flex flex-row gap-0.5 items-center">
                    <Icon icon="tabler:chevron-up" width="12" height="12" />
                    {{ formatBytes(node.net_total_up ?? 0) }}
                  </span>
                  <span class="flex flex-row gap-0.5 items-center">
                    <Icon icon="tabler:chevron-down" width="12" height="12" />
                    {{ formatBytes(node.net_total_down ?? 0) }}
                  </span>
                </div>
              </div>
            </div>

            <!-- 速率 -->
            <div v-else-if="col.key === 'rate'">
              <div class="text-[10px] flex flex-col ">
                <span class="text-green-600 flex flex-row gap-1 items-center">
                  <Icon icon="tabler:chevron-up" width="12" height="12" />
                  {{ formatBytesPerSecond(node.net_out ?? 0) }}
                </span>
                <span class="text-blue-600 flex flex-row gap-1 items-center">
                  <Icon icon="tabler:chevron-down" width="12" height="12" />
                  {{ formatBytesPerSecond(node.net_in ?? 0) }}
                </span>
              </div>
            </div>
          </template>
        </div>

        <div
          v-if="!node.online" class="absolute inset-0 z-2 p-2 bg-background/10 rounded-lg flex items-center"
          aria-hidden="true"
        >
          <div class="grid gap-2 items-center justify-center" :style="gridStyle">
            <div class="h-full space-y-1" :style="offlineOverlayContentStyle">
              <div class="text-sm font-semibold truncate">
                <span class="text-red-500">离线</span> {{ node.name }}
              </div>
              <div class="text-xs text-muted-foreground">
                {{ formatOfflineTime(node) }}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// src/components/NodeList.tsx
'use client'

import type { NodeData } from '@/stores/nodes'
import { Icon } from '@iconify/react'
import { useMemo, useState } from 'react'
import NodePingListCell from '@/components/NodePingListCell'
import TrafficProgress from '@/components/TrafficProgress'
import { Badge } from '@/components/ui/badge'
import { ProgressThin } from '@/components/ui/progress-thin'
import { DataTooltip } from '@/components/ui/tooltip'
import { useAppStore } from '@/stores/app'
import { formatBytesPerSecondWithConfig, formatBytesWithConfig, formatDateTime, formatUptimeWithFormat, getStatus } from '@/utils/helper'
import { getOSImage, getOSName } from '@/utils/osImageHelper'
import { getRegionCode, getRegionDisplayName } from '@/utils/regionHelper'
import { formatPriceWithCycle, getDaysUntilExpired, getExpireStatus, getExpireTextClass, parseTags } from '@/utils/tagHelper'

interface ColumnConfig {
  key: string
  label: string
  width: string | number
  sortable: boolean
}

interface PriceTagItem {
  text: string
  highlightValue?: string
  prefix?: string
  suffix?: string
}

const columns: ColumnConfig[] = [
  { key: 'status', label: '状态', width: '40px', sortable: false },
  { key: 'os', label: '系统', width: '40px', sortable: false },
  { key: 'name', label: '节点', width: 'minmax(160px, 0.8fr)', sortable: true },
  { key: 'tags', label: '标签', width: 'minmax(200px, 1fr)', sortable: false },
  { key: 'uptime', label: '运行时间', width: '116px', sortable: true },
  { key: 'cpu', label: 'CPU', width: '100px', sortable: false },
  { key: 'mem', label: '内存', width: '100px', sortable: false },
  { key: 'disk', label: '硬盘', width: '100px', sortable: false },
  { key: 'traffic', label: '流量', width: '100px', sortable: false },
  { key: 'rate', label: '速率', width: '80px', sortable: true },
]

function getTrafficUsed(node: NodeData): number {
  const { net_total_up = 0, net_total_down = 0, traffic_limit_type } = node
  switch (traffic_limit_type) {
    case 'up': return net_total_up
    case 'down': return net_total_down
    case 'min': return Math.min(net_total_up, net_total_down)
    case 'max': return Math.max(net_total_up, net_total_down)
    case 'sum':
    default: return net_total_up + net_total_down
  }
}

function getTrafficUsedPercentage(node: NodeData): number {
  if (node.traffic_limit <= 0)
    return 0
  return Math.min((getTrafficUsed(node) / node.traffic_limit) * 100, 100)
}

function getPriceTags(node: NodeData, lang: 'zh-CN' | 'en-US'): PriceTagItem[] {
  const tags: PriceTagItem[] = []
  if (node.price !== 0) {
    const days = getDaysUntilExpired(node.expired_at)
    const status = getExpireStatus(node.expired_at)
    const priceText = formatPriceWithCycle(node.price, node.billing_cycle, node.currency, lang)
    tags.push({ text: priceText })
    if (status === 'expired')
      tags.push({ text: lang === 'zh-CN' ? '已过期' : 'Expired' })
    else if (status === 'long_term')
      tags.push({ text: lang === 'zh-CN' ? '长期' : 'Long-term' })
    else if (lang === 'zh-CN')
      tags.push({ text: `剩余 ${days} 天`, prefix: '剩余 ', highlightValue: String(days), suffix: ' 天' })
    else
      tags.push({ text: `${days} days left`, highlightValue: String(days), suffix: ' days left' })
  }
  return tags
}

export default function NodeList({
  nodes,
  transitionKey,
  onClick,
  onPingClick,
}: {
  nodes: NodeData[]
  transitionKey?: string
  onClick: (node: NodeData) => void
  onPingClick: (node: NodeData) => void
}) {
  const [sortKey, setSortKey] = useState('')
  const [sortDir, setSortDir] = useState<1 | -1>(1)
  const byteDecimals = useAppStore(state => state.byteDecimals)
  const lang = useAppStore(state => state.lang)
  const formatBytes = (bytes: number) => formatBytesWithConfig(bytes, byteDecimals)
  const formatBytesPerSecond = (bytes: number) => formatBytesPerSecondWithConfig(bytes, byteDecimals)
  const formatUptime = (seconds: number) => formatUptimeWithFormat(seconds, 'hour')
  const gridTemplateColumns = columns.map(col => col.width).join(' ')
  const columnKeys = columns.map(col => col.key)
  const nameIndex = columnKeys.indexOf('name')
  const offlineOverlayContentStyle = { gridColumn: `${nameIndex + 1} / -1` }

  const sortedNodes = useMemo(() => {
    const sorted = [...nodes]
    if (!sortKey)
      return sorted

    return sorted.sort((a, b) => {
      switch (sortKey) {
        case 'name': {
          const va = (a.name || '').toLowerCase()
          const vb = (b.name || '').toLowerCase()
          return sortDir * (va < vb ? -1 : va > vb ? 1 : 0)
        }
        case 'uptime': return sortDir * ((a.uptime ?? 0) - (b.uptime ?? 0))
        case 'rate': return sortDir * (((a.net_out ?? 0) + (a.net_in ?? 0)) - ((b.net_out ?? 0) + (b.net_in ?? 0)))
        default: return 0
      }
    })
  }, [nodes, sortDir, sortKey])

  function handleSort(col: ColumnConfig) {
    if (!col.sortable)
      return
    if (sortKey === col.key) {
      setSortDir(value => value === 1 ? -1 : 1)
    }
    else {
      setSortKey(col.key)
      setSortDir(1)
    }
  }

  return (
    <div className="min-w-0 overflow-x-auto overflow-y-hidden p-1 -m-1">
      <div className="flex w-full min-w-fit flex-col gap-1">
        <div className="grid gap-2 rounded-lg bg-background/60 p-2 backdrop-blur-sm" style={{ gridTemplateColumns }}>
          {columns.map(col => (
            <button
              type="button"
              key={col.key}
              className={`${col.sortable ? 'cursor-pointer' : 'cursor-default'} ${['status', 'os'].includes(col.key) ? 'text-center' : 'text-left'}`}
              onClick={() => handleSort(col)}
            >
              <span className="text-xs text-muted-foreground">
                {col.label}
                {col.sortable && sortKey === col.key ? (sortDir === 1 ? ' ↑' : ' ↓') : ''}
              </span>
            </button>
          ))}
        </div>

        <div className="flex flex-col gap-1">
          {sortedNodes.map((node, index) => (
            <div
              key={transitionKey ? `${transitionKey}-${node.uuid}` : node.uuid}
              className={`relative flex h-16 cursor-pointer flex-col justify-center rounded-lg bg-background/30 px-2 shadow-[0_0_0_2px] shadow-transparent backdrop-blur-sm transition-all hover:bg-background hover:shadow-slate-500/10 ${!node.online ? '!shadow-red-600/10' : ''}`}
              style={{ animationDelay: `${Math.min(index, 12) * 35}ms` }}
              onClick={() => onClick(node)}
            >
              <div className="grid items-center gap-2" style={{ gridTemplateColumns }}>
                {columns.map(col => renderCell(col.key, node))}
              </div>
              {!node.online
                ? (
                    <div className="absolute inset-0 z-2 flex items-center rounded-lg bg-background/10 p-2" aria-hidden="true">
                      <div className="grid items-center justify-center gap-2" style={{ gridTemplateColumns }}>
                        <div className="h-full space-y-1" style={offlineOverlayContentStyle}>
                          <div className="truncate text-sm font-semibold">
                            <span className="text-red-500">离线</span>
                            {' '}
                            {node.name}
                          </div>
                          <div className="text-xs text-muted-foreground">{formatDateTime(node.time)}</div>
                        </div>
                      </div>
                    </div>
                  )
                : null}
            </div>
          ))}
        </div>
      </div>
    </div>
  )

  function renderCell(key: string, node: NodeData) {
    const mutedClass = !node.online ? 'blur-sm opacity-30' : ''

    switch (key) {
      case 'status':
        return (
          <div key={key} className="flex justify-center">
            <div className={`relative size-2 rounded-full ${node.online ? 'bg-green-600' : 'bg-red-600'}`}>
              <div className={`absolute inset-0 animate-ping rounded-full opacity-50 ${node.online ? 'bg-green-600' : 'bg-red-600'}`} />
            </div>
          </div>
        )
      case 'os':
        return <div key={key} className="flex justify-center"><img src={getOSImage(node.os)} alt={getOSName(node.os)} className="size-4" /></div>
      case 'name': {
        const priceTags = getPriceTags(node, lang)
        return (
          <div key={key} className={`space-y-0.5 ${mutedClass}`}>
            <div className="flex items-center gap-1 text-xs font-semibold">
              {node.region?.trim() ? <img src={`/images/flags/${getRegionCode(node.region)}.svg`} alt={getRegionDisplayName(node.region)} className="size-5 rounded-sm" /> : null}
              <span className="truncate">{node.name}</span>
            </div>
            {priceTags.length > 0
              ? (
                  <div className="truncate text-[11px] text-muted-foreground/70">
                    {priceTags.map((tag, tagIndex) => (
                      <span key={`${tag.text}-${tagIndex}`} className={tagIndex ? 'ml-1' : ''}>
                        {tag.highlightValue
                          ? (
                              <>
                                <span>{tag.prefix}</span>
                                <span className={getExpireTextClass(node.expired_at)}>{tag.highlightValue}</span>
                                <span>{tag.suffix}</span>
                              </>
                            )
                          : tag.text}
                      </span>
                    ))}
                  </div>
                )
              : null}
          </div>
        )
      }
      case 'tags':
        return (
          <div key={key}>
            <div className="flex flex-wrap items-center gap-1">
              {parseTags(node.tags).map((tag, tagIndex) => (
                <Badge key={`${tag.text}-${tagIndex}`} variant="outline" className="rounded border-muted-foreground/10 px-1.5 !text-[11px] text-muted-foreground">{tag.text}</Badge>
              ))}
            </div>
          </div>
        )
      case 'uptime':
        return (
          <div key={key} className="flex flex-col gap-0.5">
            <span className="truncate text-[10px] text-muted-foreground">{formatUptime(node.uptime ?? 0)}</span>
            <button
              type="button"
              className="outline-none"
              aria-label={`${node.name} 延迟 / 丢包`}
              onClick={(event) => {
                event.stopPropagation()
                onPingClick(node)
              }}
            >
              <NodePingListCell uuid={node.uuid} online={node.online} />
            </button>
          </div>
        )
      case 'cpu':
        return (
          <div key={key} className="group">
            <div className="space-y-1">
              <div className="truncate text-[10px] text-muted-foreground">
                <span className="inline group-hover:hidden">
                  {(node.cpu ?? 0).toFixed(1)}
                  %
                </span>
                <span className="hidden group-hover:inline">
                  {(node.load ?? 0).toFixed(2)}
                  ,
                  {' '}
                  {(node.load5 ?? 0).toFixed(2)}
                  ,
                  {' '}
                  {(node.load15 ?? 0).toFixed(2)}
                </span>
              </div>
              <ProgressThin percentage={node.cpu ?? 0} status={getStatus(node.cpu ?? 0)} height={4} />
            </div>
          </div>
        )
      case 'mem': {
        const memPercentage = (node.ram ?? 0) / (node.mem_total || 1) * 100
        return (
          <div key={key} className="group">
            <DataTooltip
              placement="top"
              className="block"
              content={(
                <>
                  <div className="flex items-center justify-between gap-3 whitespace-nowrap">
                    <span className="text-background/70">USED</span>
                    <span>{formatBytes(node.ram ?? 0)}</span>
                  </div>
                  {node.swap
                    ? (
                        <div className="flex items-center justify-between gap-3 whitespace-nowrap">
                          <span className="text-background/70">SWAP</span>
                          <span>{formatBytes(node.swap ?? 0)}</span>
                        </div>
                      )
                    : null}
                </>
              )}
              contentClass="px-1.5 py-1 text-[10px]"
            >
              <div className="space-y-1">
                <div className="truncate text-[10px] text-muted-foreground">
                  <span className="inline group-hover:hidden">
                    {memPercentage.toFixed(1)}
                    %
                  </span>
                  <span className="hidden group-hover:inline">
                    {formatBytes(node.ram ?? 0)}
                    {' '}
                    /
                    {' '}
                    {formatBytes(node.mem_total ?? 0)}
                  </span>
                </div>
                <ProgressThin percentage={memPercentage} status={getStatus(memPercentage)} height={4} />
              </div>
            </DataTooltip>
          </div>
        )
      }
      case 'disk': {
        const diskPercentage = (node.disk ?? 0) / (node.disk_total || 1) * 100
        return (
          <div key={key} className="group">
            <div className="space-y-1">
              <div className="truncate text-[10px] text-muted-foreground">
                <span className="inline group-hover:hidden">
                  {diskPercentage.toFixed(1)}
                  %
                </span>
                <span className="hidden group-hover:inline">
                  {formatBytes(node.disk ?? 0)}
                  {' '}
                  /
                  {' '}
                  {formatBytes(node.disk_total ?? 0)}
                </span>
              </div>
              <ProgressThin percentage={diskPercentage} status={getStatus(diskPercentage)} height={4} />
            </div>
          </div>
        )
      }
      case 'traffic':
        return (
          <div key={key} className="group">
            <DataTooltip
              placement="top"
              className="flex items-center gap-2"
              content={(
                <>
                  <span className="flex items-center gap-0.5 whitespace-nowrap">
                    <Icon icon="tabler:chevron-up" width={12} height={12} />
                    {formatBytes(node.net_total_up ?? 0)}
                  </span>
                  <span className="flex items-center gap-0.5 whitespace-nowrap">
                    <Icon icon="tabler:chevron-down" width={12} height={12} />
                    {formatBytes(node.net_total_down ?? 0)}
                  </span>
                </>
              )}
              contentClass="mb-1.5"
            >
              <div className="w-full space-y-1">
                <div className="truncate text-[10px] text-muted-foreground">
                  <span className="inline group-hover:hidden">
                    {getTrafficUsedPercentage(node).toFixed(1)}
                    %
                  </span>
                  <span className="hidden group-hover:inline">
                    {formatBytes(getTrafficUsed(node))}
                    {' '}
                    /
                    {' '}
                    {node.traffic_limit > 0 ? formatBytes(node.traffic_limit) : '∞'}
                  </span>
                </div>
                <TrafficProgress upload={node.net_total_up ?? 0} download={node.net_total_down ?? 0} trafficLimit={node.traffic_limit} trafficLimitType={node.traffic_limit_type || 'sum'} height="4px" />
              </div>
            </DataTooltip>
          </div>
        )
      case 'rate':
        return (
          <div key={key}>
            <div className="flex flex-col text-[10px]">
              <span className="flex flex-row items-center gap-1 text-green-600">
                <Icon icon="tabler:chevron-up" width={12} height={12} />
                {formatBytesPerSecond(node.net_out ?? 0)}
              </span>
              <span className="flex flex-row items-center gap-1 text-blue-600">
                <Icon icon="tabler:chevron-down" width={12} height={12} />
                {formatBytesPerSecond(node.net_in ?? 0)}
              </span>
            </div>
          </div>
        )
      default:
        return <div key={key} />
    }
  }
}
