// src/components/charts/PingChart.tsx
"use client";

import dynamic from "next/dynamic";
import dayjs from "dayjs";
import { useEffect, useMemo, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Empty } from "@/components/ui/EmptyCompat";
import { Spinner } from "@/components/ui/spinner";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useAppStore } from "@/stores/app";
import { cutPeakValues, interpolateNullsLinear } from "@/utils/recordHelper";
import { getSharedRpc } from "@/utils/rpc";
import "@/utils/echarts";

const ReactECharts = dynamic(() => import("echarts-for-react"), { ssr: false });

interface PingRecord {
  client: string;
  task_id: number;
  time: string;
  value: number;
}

interface TaskInfo {
  id: number;
  name: string;
  interval: number;
  loss: number;
  p99?: number;
  p50?: number;
  min?: number;
  max?: number;
  avg?: number;
  latest?: number;
  type?: string;
}

interface PingChartProps {
  uuid: string;
  className?: string;
}

const CHART_COLORS = [
  "#FF6B6B", "#4ECDC4", "#A78BFA", "#60A5FA",
  "#FFB347", "#F472B6", "#34D399", "#FB923C",
];

const PRESET_VIEWS = [
  { label: "1 小时", hours: 1 },
  { label: "6 小时", hours: 6 },
  { label: "12 小时", hours: 12 },
  { label: "1 天", hours: 24 },
];

export function PingChart({ uuid, className }: PingChartProps) {
  const appStore = useAppStore();
  const maxHours = appStore.publicSettings?.ping_record_preserve_time || 168;
  const isDark = useThemeDarkProxy();

  const availableViews = useMemo(() => {
    const views: { label: string; hours: number }[] = [];
    for (const v of PRESET_VIEWS) if (maxHours >= v.hours) views.push(v);
    if (maxHours > 24) {
      const label = maxHours % 24 === 0 ? `${maxHours / 24} 天` : `${maxHours} 小时`;
      views.push({ label, hours: maxHours });
    } else if (maxHours > 1 && !PRESET_VIEWS.some((v) => v.hours === maxHours)) {
      const label = maxHours % 24 === 0 ? `${maxHours / 24} 天` : `${maxHours} 小时`;
      views.push({ label, hours: maxHours });
    }
    return views;
  }, [maxHours]);

  const [selectedView, setSelectedView] = useState<string>("");
  const [records, setRecords] = useState<PingRecord[]>([]);
  const [tasks, setTasks] = useState<TaskInfo[]>([]);
  const [selectedTaskIds, setSelectedTaskIds] = useState<number[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showDelay, setShowDelay] = useState(true);
  const [showLoss, setShowLoss] = useState(true);
  const [cutPeak, setCutPeak] = useState(false);

  const selectedHours = useMemo(() => {
    const view = availableViews.find((v) => v.label === selectedView);
    return view?.hours || 1;
  }, [selectedView, availableViews]);

  // Set default view
  useEffect(() => {
    if (!selectedView && availableViews[0]) setSelectedView(availableViews[0].label);
  }, [availableViews, selectedView]);

  // Fetch records
  useEffect(() => {
    if (!uuid || !selectedView) return;
    let cancelled = false;
    (async () => {
      setLoading(true);
      setError(null);
      try {
        const rpc = getSharedRpc();
        const result = await rpc.getClient().call<{
          records?: PingRecord[];
          tasks?: TaskInfo[];
        }>("common:getRecords", { uuid, type: "ping", hours: selectedHours });
        if (cancelled) return;
        const recs = (result?.records || []).sort(
          (a, b) => dayjs(a.time).valueOf() - dayjs(b.time).valueOf(),
        );
        setRecords(recs);
        const newTasks = result?.tasks || [];
        setTasks(newTasks);
        if (newTasks.length > 0 && selectedTaskIds.length === 0) {
          setSelectedTaskIds(newTasks.map((t) => t.id));
        }
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : "获取数据失败");
          setRecords([]);
          setTasks([]);
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [uuid, selectedHours, selectedView]);

  // Group records by task_id, build time series
  const chartData = useMemo(() => {
    if (!records.length) return [];
    const grouped = new Map<number, PingRecord[]>();
    for (const r of records) {
      if (!selectedTaskIds.includes(r.task_id)) continue;
      const list = grouped.get(r.task_id) ?? [];
      list.push(r);
      grouped.set(r.task_id, list);
    }
    const allTimes = new Set<number>();
    for (const list of grouped.values()) {
      for (const r of list) allTimes.add(dayjs(r.time).valueOf());
    }
    const times = [...allTimes].sort((a, b) => a - b);
    const map: Record<string, number | null> = {};
    for (const t of times) map[t] = null;

    const data: Record<string, Record<string, number | null>> = {};
    for (const [taskId, list] of grouped) {
      const task = tasks.find((t) => t.id === taskId);
      const key = String(taskId);
      data[key] = { ...map };
      for (const r of list) {
        const k = String(dayjs(r.time).valueOf());
        // value < 0 means loss
        data[key][k] = r.value >= 0 ? r.value : null;
      }
    }
    const lossData: Record<string, Record<string, number | null>> = {};
    for (const [taskId, list] of grouped) {
      const key = String(taskId);
      const buckets = new Map<string, { total: number; lost: number }>();
      for (const r of list) {
        const tBucket = dayjs(r.time).startOf("minute").valueOf();
        const k = String(tBucket);
        const b = buckets.get(k) ?? { total: 0, lost: 0 };
        b.total += 1;
        if (r.value < 0) b.lost += 1;
        buckets.set(k, b);
      }
      const obj: Record<string, number | null> = {};
      for (const [k, b] of buckets) {
        obj[k] = b.total > 0 ? (b.lost / b.total) * 100 : 0;
      }
      lossData[key] = obj;
    }

    // Convert to arrays sorted by time
    const sortedKeys = [...allTimes].sort((a, b) => a - b).map(String);
    const result: {
      time: number;
      timeLabel: string;
      latency: Record<string, number | null>;
      loss: Record<string, number | null>;
    }[] = sortedKeys.map((k) => ({
      time: Number(k),
      timeLabel: dayjs(Number(k)).format("HH:mm"),
      latency: Object.fromEntries(Object.entries(data).map(([tid, o]) => [tid, o[k] ?? null])),
      loss: Object.fromEntries(Object.entries(lossData).map(([tid, o]) => [tid, o[k] ?? null])),
    }));

    if (cutPeak) {
      return result.map((row) => ({
        ...row,
        latency: Object.fromEntries(
          Object.entries(row.latency).map(([k, v]) => [k, v !== null && v > 5000 ? null : v]),
        ),
      }));
    }
    return result;
  }, [records, tasks, selectedTaskIds, cutPeak]);

  const themeColors = useMemo(
    () => ({
      text: isDark ? "rgba(255,255,255,0.85)" : "rgba(0,0,0,0.85)",
      textSecondary: isDark ? "rgba(255,255,255,0.55)" : "rgba(0,0,0,0.55)",
      splitLine: isDark ? "rgba(255,255,255,0.06)" : "rgba(0,0,0,0.06)",
      tooltipBg: isDark ? "rgba(40,40,40,0.95)" : "rgba(255,255,255,0.8)",
    }),
    [isDark],
  );

  const xAxisData = chartData.map((r) => r.timeLabel);

  const latencyChartOption = useMemo(() => {
    const taskList = tasks.filter((t) => selectedTaskIds.includes(t.id));
    return {
      animation: false,
      color: CHART_COLORS,
      tooltip: { trigger: "axis" as const, backgroundColor: themeColors.tooltipBg, borderWidth: 0, textStyle: { color: themeColors.text, fontSize: 12 } },
      legend: { textStyle: { color: themeColors.textSecondary, fontSize: 11 }, top: 0, type: "scroll" },
      grid: { top: 40, right: 24, bottom: 32, left: 56 },
      xAxis: {
        type: "category" as const,
        data: xAxisData,
        axisLabel: { fontSize: 11, color: themeColors.textSecondary },
        axisLine: { show: false },
        axisTick: { show: false },
      },
      yAxis: {
        type: "value" as const,
        name: "延迟 (ms)",
        nameTextStyle: { color: themeColors.textSecondary, padding: [0, 40, 0, 0] },
        axisLabel: { fontSize: 11, color: themeColors.textSecondary, formatter: "{value} ms" },
        splitLine: { lineStyle: { color: themeColors.splitLine, type: "dashed" as const } },
      },
      series: taskList.map((task, idx) => ({
        name: task.name,
        type: "line",
        data: chartData.map((r) => r.latency[String(task.id)]),
        showSymbol: false,
        smooth: false,
        lineStyle: { width: 1.5, color: CHART_COLORS[idx % CHART_COLORS.length] },
        connectNulls: false,
      })),
    };
  }, [chartData, tasks, selectedTaskIds, xAxisData, themeColors]);

  const lossChartOption = useMemo(() => {
    const taskList = tasks.filter((t) => selectedTaskIds.includes(t.id));
    return {
      animation: false,
      color: CHART_COLORS,
      tooltip: { trigger: "axis" as const, backgroundColor: themeColors.tooltipBg, borderWidth: 0, textStyle: { color: themeColors.text, fontSize: 12 }, valueFormatter: (val: number) => `${val.toFixed(2)}%` },
      legend: { textStyle: { color: themeColors.textSecondary, fontSize: 11 }, top: 0, type: "scroll" },
      grid: { top: 40, right: 24, bottom: 32, left: 56 },
      xAxis: {
        type: "category" as const,
        data: xAxisData,
        axisLabel: { fontSize: 11, color: themeColors.textSecondary },
        axisLine: { show: false },
        axisTick: { show: false },
      },
      yAxis: {
        type: "value" as const,
        name: "丢包 (%)",
        max: 100,
        nameTextStyle: { color: themeColors.textSecondary, padding: [0, 40, 0, 0] },
        axisLabel: { fontSize: 11, color: themeColors.textSecondary, formatter: "{value}%" },
        splitLine: { lineStyle: { color: themeColors.splitLine, type: "dashed" as const } },
      },
      series: taskList.map((task, idx) => ({
        name: task.name,
        type: "line",
        data: chartData.map((r) => r.loss[String(task.id)]),
        showSymbol: false,
        lineStyle: { width: 1.5, color: CHART_COLORS[idx % CHART_COLORS.length] },
        areaStyle: { opacity: 0.1 },
      })),
    };
  }, [chartData, tasks, selectedTaskIds, xAxisData, themeColors]);

  return (
    <Card className={className}>
      <CardHeader className="flex flex-row items-center justify-between gap-2 pb-2 flex-wrap">
        <CardTitle className="text-base">Ping 历史</CardTitle>
        <div className="flex items-center gap-2 flex-wrap">
          <Tabs value={selectedView} onValueChange={setSelectedView}>
            <TabsList>
              {availableViews.map((v) => (
                <TabsTrigger key={v.label} value={v.label} className="text-xs">{v.label}</TabsTrigger>
              ))}
            </TabsList>
          </Tabs>
          <button
            type="button"
            onClick={() => setShowDelay((v) => !v)}
            className={`text-xs px-2 py-0.5 rounded border ${showDelay ? "bg-primary/10 border-primary/30 text-primary" : "border-border text-muted-foreground"}`}
          >
            延迟
          </button>
          <button
            type="button"
            onClick={() => setShowLoss((v) => !v)}
            className={`text-xs px-2 py-0.5 rounded border ${showLoss ? "bg-primary/10 border-primary/30 text-primary" : "border-border text-muted-foreground"}`}
          >
            丢包
          </button>
          <button
            type="button"
            onClick={() => setCutPeak((v) => !v)}
            className={`text-xs px-2 py-0.5 rounded border ${cutPeak ? "bg-primary/10 border-primary/30 text-primary" : "border-border text-muted-foreground"}`}
          >
            去峰值
          </button>
        </div>
      </CardHeader>
      <CardContent>
        {loading ? (
          <div className="flex h-64 items-center justify-center"><Spinner /></div>
        ) : error ? (
          <div className="flex h-64 items-center justify-center text-destructive">{error}</div>
        ) : !chartData.length ? (
          <div className="flex h-64 items-center justify-center">
            <Empty description="暂无数据" />
          </div>
        ) : (
          <div className="space-y-4">
            {showDelay && <ReactECharts option={latencyChartOption} style={{ height: 240, width: "100%" }} notMerge lazyUpdate />}
            {showLoss && <ReactECharts option={lossChartOption} style={{ height: 200, width: "100%" }} notMerge lazyUpdate />}
            {tasks.length > 1 && (
              <div className="flex flex-wrap gap-2 pt-2">
                {tasks.map((t, idx) => (
                  <button
                    key={t.id}
                    type="button"
                    onClick={() => {
                      setSelectedTaskIds((cur) =>
                        cur.includes(t.id) ? cur.filter((x) => x !== t.id) : [...cur, t.id],
                      );
                    }}
                    className={`text-xs px-2 py-1 rounded border flex items-center gap-1 ${
                      selectedTaskIds.includes(t.id) ? "bg-primary/10 border-primary/30" : "border-border text-muted-foreground"
                    }`}
                  >
                    <span className="size-2 rounded-full" style={{ background: CHART_COLORS[idx % CHART_COLORS.length] }} />
                    {t.name}
                  </button>
                ))}
              </div>
            )}
          </div>
        )}
      </CardContent>
    </Card>
  );
}

function useThemeDarkProxy(): boolean {
  const [dark, setDark] = useState(false);
  useEffect(() => {
    if (typeof document === "undefined") return;
    const obs = new MutationObserver(() => setDark(document.documentElement.classList.contains("dark")));
    obs.observe(document.documentElement, { attributes: true, attributeFilter: ["class"] });
    setDark(document.documentElement.classList.contains("dark"));
    return () => obs.disconnect();
  }, []);
  return dark;
}

export default PingChart;

// src/components/PingChart.vue
<script setup lang="ts">
import { Icon } from '@iconify/vue'
import dayjs from 'dayjs'
import { computed, onMounted, ref, shallowRef, watch } from 'vue'
import VChart from 'vue-echarts'
import { Button } from '@/components/ui/button'
import { Empty } from '@/components/ui/empty'
import { Spinner } from '@/components/ui/spinner'
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip'
import { useAppStore } from '@/stores/app'
import { cutPeakValues, interpolateNullsLinear } from '@/utils/recordHelper'
import { getSharedRpc } from '@/utils/rpc'
import '@/utils/echarts' // 共享 ECharts 配置

const props = defineProps<{
  uuid: string
}>()

const appStore = useAppStore()
const isDark = computed(() => appStore.isDark)
// 使用共享的 RPC 实例，避免重复创建连接
const rpc = getSharedRpc()

// 图表主题相关颜色
const chartThemeColors = computed(() => ({
  text: isDark.value ? 'rgba(255, 255, 255, 0.85)' : 'rgba(0, 0, 0, 0.85)',
  textSecondary: isDark.value ? 'rgba(255, 255, 255, 0.55)' : 'rgba(0, 0, 0, 0.55)',
  textTertiary: isDark.value ? 'rgba(255, 255, 255, 0.35)' : 'rgba(0, 0, 0, 0.35)',
  borderColor: isDark.value ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.06)',
  splitLineColor: isDark.value ? 'rgba(255, 255, 255, 0.06)' : 'rgba(0, 0, 0, 0.06)',
  tooltipBg: isDark.value ? 'rgba(40, 40, 40, 0.95)' : 'rgba(255, 255, 255, 0.8)',
  tooltipShadow: isDark.value ? 'rgba(0, 0, 0, 0.4)' : 'rgba(0, 0, 0, 0.1)',
  crosshairColor: isDark.value ? 'rgba(255, 255, 255, 0.15)' : 'rgba(0, 0, 0, 0.1)',
}))

// 优化后的图表配色方案（多任务时使用）
const chartColors = [
  '#FF6B6B', // 珊瑚红
  '#4ECDC4', // 青绿色
  '#A78BFA', // 紫罗兰
  '#60A5FA', // 天蓝色
  '#FFB347', // 琥珀黄
  '#F472B6', // 粉红色
  '#34D399', // 翠绿色
  '#FB923C', // 橙色
]

// 从 publicSettings 获取记录保留时间
const maxPingRecordPreserveTime = computed(() => appStore.publicSettings?.ping_record_preserve_time || 168)

// 视图选项
const presetViews = [
  { label: '1 小时', hours: 1 },
  { label: '6 小时', hours: 6 },
  { label: '12 小时', hours: 12 },
  { label: '1 天', hours: 24 },
]

// 可用视图列表
const availableViews = computed(() => {
  const views: { label: string, hours: number }[] = []
  const maxHours = maxPingRecordPreserveTime.value

  for (const v of presetViews) {
    if (maxHours >= v.hours) {
      views.push(v)
    }
  }

  const maxPreset = presetViews[presetViews.length - 1]
  if (maxPreset && maxHours > maxPreset.hours) {
    const label = maxHours % 24 === 0
      ? `${Math.floor(maxHours / 24)} 天`
      : `${maxHours} 小时`
    views.push({ label, hours: maxHours })
  }
  else if (maxHours > 1 && !presetViews.some(v => v.hours === maxHours)) {
    const label = maxHours % 24 === 0
      ? `${Math.floor(maxHours / 24)} 天`
      : `${maxHours} 小时`
    views.push({ label, hours: maxHours })
  }

  return views
})

// 当前选中的视图
const selectedView = ref<string>('')
const selectedHours = computed(() => {
  const view = availableViews.value.find(v => v.label === selectedView.value)
  return view?.hours || 1
})

// 初始化默认视图
watch(availableViews, (views) => {
  const firstView = views[0]
  if (firstView && !selectedView.value) {
    selectedView.value = firstView.label
  }
}, { immediate: true })

// ==================== 类型定义 ====================

interface PingRecord {
  client: string
  task_id: number
  time: string
  value: number
}

interface TaskInfo {
  id: number
  name: string
  interval: number
  loss: number
  p99?: number
  p50?: number
  p99_p50_ratio?: number
  min?: number
  max?: number
  avg?: number
  latest?: number
  total?: number
  type?: string
}

interface PingRecordsResponse {
  count: number
  records: PingRecord[]
  tasks?: TaskInfo[]
  from?: string
  to?: string
}

// 数据状态
const remoteData = shallowRef<PingRecord[]>([])
const tasks = shallowRef<TaskInfo[]>([])
const loading = ref(false)
const error = ref<string | null>(null)

// 任务选择
const selectedTaskIds = ref<number[]>([])
const cutPeak = ref(false)

const chartMargin = { top: 30, right: 24, bottom: 52, left: 56 }

// ==================== 数据获取 ====================

async function fetchRecords() {
  if (!props.uuid)
    return

  loading.value = true
  error.value = null

  try {
    const result = await rpc.getClient().call<PingRecordsResponse>('common:getRecords', {
      uuid: props.uuid,
      type: 'ping',
      hours: selectedHours.value,
    })

    const records = result?.records || []
    records.sort((a, b) => dayjs(a.time).valueOf() - dayjs(b.time).valueOf())

    remoteData.value = records
    tasks.value = result?.tasks || []

    if (tasks.value.length > 0 && selectedTaskIds.value.length === 0) {
      selectedTaskIds.value = tasks.value.map(t => t.id)
    }
  }
  catch (err) {
    error.value = err instanceof Error ? err.message : '获取数据失败'
    remoteData.value = []
    tasks.value = []
  }
  finally {
    loading.value = false
  }
}

// ==================== 数据处理 ====================

const mergedData = computed(() => {
  const data = remoteData.value
  if (!data.length)
    return []

  const taskList = tasks.value

  const taskIntervals = taskList
    .map(t => t.interval)
    .filter((v): v is number => typeof v === 'number' && v > 0)

  const fallbackIntervalSec = taskIntervals.length ? Math.min(...taskIntervals) : 60
  const toleranceMs = Math.min(
    6000,
    Math.max(800, Math.floor(fallbackIntervalSec * 1000 * 0.25)),
  )

  const grouped: Map<number, Record<string, unknown>> = new Map()
  const anchors: number[] = []

  for (const rec of data) {
    const ts = dayjs(rec.time).valueOf()
    let anchor: number | null = null

    for (const a of anchors) {
      if (Math.abs(a - ts) <= toleranceMs) {
        anchor = a
        break
      }
    }

    const useTs = anchor ?? ts
    if (!grouped.has(useTs)) {
      grouped.set(useTs, { time: dayjs(useTs).toISOString() })
      if (anchor === null) {
        anchors.push(useTs)
      }
    }

    const group = grouped.get(useTs)!
    group[rec.task_id] = rec.value < 0 ? null : rec.value
  }

  const merged = Array.from(grouped.values()).sort(
    (a, b) => dayjs(a.time as string).valueOf() - dayjs(b.time as string).valueOf(),
  )

  const hours = selectedHours.value
  const lastItem = merged[merged.length - 1]
  const lastTs = lastItem ? dayjs(lastItem.time as string).valueOf() : dayjs().valueOf()
  const fromTs = lastTs - hours * 3600_000

  let startIdx = 0
  for (let i = 0; i < merged.length; i++) {
    const item = merged[i]
    if (!item)
      continue
    const ts = dayjs(item.time as string).valueOf()
    if (ts >= fromTs) {
      startIdx = Math.max(0, i - 1)
      break
    }
  }

  return merged.slice(startIdx)
})

const chartData = computed(() => {
  let data = mergedData.value
  const selectedKeys = selectedTaskIds.value.map(String)

  if (selectedKeys.length === 0)
    return []

  if (cutPeak.value) {
    data = cutPeakValues(data, selectedKeys)
  }

  if (selectedKeys.length > 0 && data.length > 0) {
    data = interpolateNullsLinear(data, selectedKeys, {
      maxGapMultiplier: 6,
      minCapMs: 2 * 60_000,
      maxCapMs: 30 * 60_000,
    })
  }

  return data
})

// ==================== 工具函数 ====================

function formatTime(time: string, showDate: boolean): string {
  const date = dayjs(time)
  if (showDate) {
    return date.format('M/D HH:mm')
  }
  return date.format('HH:mm')
}

function formatTimeForTooltip(time: string, hours: number): string {
  const date = dayjs(time)
  if (hours < 24) {
    return date.format('HH:mm:ss')
  }
  return date.format('MM/DD HH:mm')
}

const showDateInAxis = computed(() => selectedHours.value >= 24)

// ==================== 任务选择 ====================

// 获取任务颜色（根据任务在完整列表中的索引）
function getTaskColor(taskId: number): string {
  const taskIndex = tasks.value.findIndex(t => t.id === taskId)
  const safeIndex = Math.max(0, taskIndex % chartColors.length)
  return chartColors[safeIndex]!
}

// 最新值统计（从服务端 tasks 获取，保持颜色顺序）
const latestValues = computed(() => {
  if (!tasks.value.length)
    return []

  const latestMap = new Map<number, number | null>()
  for (const task of tasks.value) {
    for (let i = remoteData.value.length - 1; i >= 0; i--) {
      const rec = remoteData.value[i]
      if (rec && rec.task_id === task.id && rec.value >= 0) {
        latestMap.set(task.id, rec.value)
        break
      }
    }
  }

  return tasks.value.map((task, idx) => {
    const safeIdx = Math.max(0, idx % chartColors.length)
    return {
      ...task,
      latestValue: latestMap.get(task.id) ?? null,
      color: chartColors[safeIdx]!,
    }
  })
})

const selectedTasks = computed(() => {
  return tasks.value.filter(t => selectedTaskIds.value.includes(t.id))
})

// 切换任务选中状态
function toggleTask(taskId: number) {
  if (selectedTaskIds.value.includes(taskId)) {
    selectedTaskIds.value = selectedTaskIds.value.filter(id => id !== taskId)
  }
  else {
    selectedTaskIds.value = [...selectedTaskIds.value, taskId]
  }
}

function showAllTasks() {
  selectedTaskIds.value = tasks.value.map(t => t.id)
}

function hideAllTasks() {
  selectedTaskIds.value = []
}

// ==================== 图表配置 ====================

// 通用 Tooltip 配置
const baseTooltipConfig = computed(() => ({
  trigger: 'axis' as const,
  confine: false,
  backgroundColor: chartThemeColors.value.tooltipBg,
  borderColor: 'transparent',
  borderWidth: 0,
  borderRadius: 6,
  textStyle: {
    color: chartThemeColors.value.text,
    fontSize: 12,
    lineHeight: 20,
  },
  extraCssText: `backdrop-filter: blur(4px);z-index:9;box-shadow:0 0 10px ${chartThemeColors.value.tooltipShadow}`,
  axisPointer: {
    type: 'cross' as const,
    crossStyle: {
      color: chartThemeColors.value.textTertiary,
    },
    lineStyle: {
      color: chartThemeColors.value.crosshairColor,
      width: 1,
      type: 'dashed' as const,
    },
    shadowStyle: {
      color: chartThemeColors.value.crosshairColor,
    },
  },
}))

const pingChartOption = computed(() => {
  const taskList = selectedTasks.value
  const data = chartData.value
  const hours = selectedHours.value

  // 构建 series，确保颜色与卡片一致
  const series = taskList.map((task) => {
    const color = getTaskColor(task.id)
    return {
      name: task.name,
      type: 'line' as const,
      data: data.map(d => d[task.id] as number | null ?? null),
      smooth: cutPeak.value ? 0.6 : 0.1,
      showSymbol: false,
      connectNulls: false,
      lineStyle: { width: 1.5, color, cap: 'round' as const },
      itemStyle: { color }, // 确保 symbol 颜色一致
    }
  })

  // 颜色映射表（用于 Tooltip）
  const colorMap = new Map<number, string>()
  tasks.value.forEach((task, idx) => {
    const safeIdx = Math.max(0, idx % chartColors.length)
    colorMap.set(task.id, chartColors[safeIdx]!)
  })

  return {
    animation: false,
    // 全局颜色设置（用于图例等）
    color: tasks.value.map((_, idx) => {
      const safeIdx = Math.max(0, idx % chartColors.length)
      return chartColors[safeIdx]!
    }),
    tooltip: {
      ...baseTooltipConfig.value,
      formatter: (params: unknown) => {
        const p = params as Array<{ seriesName: string, value: number | null, dataIndex: number }>
        if (!p.length)
          return ''
        const firstParam = p[0]
        if (!firstParam)
          return ''
        const rowData = data[firstParam.dataIndex]
        if (!rowData)
          return ''

        const time = rowData.time as string
        const timeStr = formatTimeForTooltip(time, hours)
        let html = `<div style="font-weight:600;margin-bottom:6px;color:${chartThemeColors.value.textSecondary}">${timeStr}</div>`
        html += '<div style="display:flex;flex-direction:column;gap:4px">'

        // 按延迟值排序显示
        const sortedParams = [...p].sort((a, b) => (a.value ?? 0) - (b.value ?? 0))

        for (const item of sortedParams) {
          if (item.value !== null && item.value !== undefined) {
            // 通过任务名找到对应的任务ID，再获取颜色
            const task = tasks.value.find(t => t.name === item.seriesName)
            const color = task ? colorMap.get(task.id) || chartColors[0] : chartColors[0]
            const colorDot = `<span style="display:inline-block;width:8px;height:8px;border-radius:50%;background:${color};margin-right:8px;flex-shrink:0"></span>`
            html += `<div style="display:flex;align-items:center">${colorDot}<span style="flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${item.seriesName}</span><span style="margin-left:auto;font-weight:600;margin-left:16px;font-variant-numeric:tabular-nums">${Math.round(item.value)} ms</span></div>`
          }
        }
        html += '</div>'
        return html
      },
    },
    legend: {
      type: 'scroll',
      bottom: 0,
      itemWidth: 12,
      itemHeight: 12,
      itemGap: 16,
      icon: 'roundRect',
      textStyle: { fontSize: 11, color: chartThemeColors.value.textSecondary },
      data: taskList.map(t => t.name),
    },
    grid: chartMargin,
    xAxis: {
      type: 'category',
      data: data.map(d => formatTime(d.time as string, showDateInAxis.value)),
      axisLabel: {
        fontSize: 11,
        color: chartThemeColors.value.textSecondary,
        margin: 12,
      },
      axisLine: {
        show: true,
        lineStyle: { color: chartThemeColors.value.borderColor, width: 1 },
      },
      axisTick: { show: false },
      boundaryGap: false,
    },
    yAxis: {
      type: 'value',
      name: '延迟 (ms)',
      nameTextStyle: { color: chartThemeColors.value.textSecondary },
      axisLabel: { fontSize: 11, color: chartThemeColors.value.textSecondary, formatter: '{value}' },
      axisLine: { show: false },
      axisTick: { show: false },
      splitLine: {
        lineStyle: {
          color: chartThemeColors.value.splitLineColor,
          type: 'dashed' as const,
        },
      },
    },
    series,
  }
})

// ==================== 生命周期 ====================

watch(selectedView, () => {
  selectedTaskIds.value = []
  fetchRecords()
})

watch(() => props.uuid, () => {
  remoteData.value = []
  tasks.value = []
  selectedTaskIds.value = []
  fetchRecords()
})

onMounted(() => {
  const firstView = availableViews.value[0]
  if (firstView && !selectedView.value) {
    selectedView.value = firstView.label
  }
  fetchRecords()
})
</script>

<template>
  <div class="flex flex-col gap-4">
    <!-- 时间选择器 -->
    <div class="flex flex-wrap gap-2 justify-center">
      <Button
        v-for="view in availableViews" :key="view.label"
        :variant="selectedView === view.label ? 'default' : 'outline'" size="sm" @click="selectedView = view.label"
      >
        {{ view.label }}
      </Button>
    </div>

    <!-- 内容区域 -->
    <Spinner :show="loading" content-class="flex flex-col gap-4">
      <div v-if="error" class="text-red-500 py-8 text-center">
        {{ error }}
      </div>
      <div v-else-if="tasks.length === 0 && !loading" class="py-8">
        <Empty description="暂无延迟数据" />
      </div>

      <template v-else>
        <!-- 最新值统计卡片（可点击切换选中状态） -->
        <div
          v-if="latestValues.length > 0" class="gap-3 grid"
          style="grid-template-columns: repeat(auto-fit, minmax(240px, 1fr))"
        >
          <div
            v-for="task in latestValues" :key="task.id"
            class="p-2 rounded-md bg-background/50 hover:bg-background hover:shadow-[0_0_0_2px] hover:shadow-primary/10 flex gap-3 cursor-pointer select-none transition-all items-center"
            :class="[!selectedTaskIds.includes(task.id) && 'opacity-30']"
            :onmouseover="(e: MouseEvent) => ((e.currentTarget as HTMLElement).style.borderColor = task.color)"
            :onmouseout="(e: MouseEvent) => ((e.currentTarget as HTMLElement).style.borderColor = '')"
            @click="toggleTask(task.id)"
          >
            <div class="flex-1 min-w-0">
              <TooltipProvider>
                <div class="flex gap-2 items-center">
                  <div class="rounded h-4 w-1" :style="{ backgroundColor: task.color }" />
                  <span class="text-sm font-semibold truncate">{{ task.name }}</span>
                  <div class="flex-1" />
                  <Tooltip>
                    <TooltipTrigger as-child>
                      <span
                        class="text-sm opacity-50 cursor-help transition-opacity hover:opacity-100 inline-flex"
                        style="color: color-mix(in srgb, hsl(var(--foreground)) 80%, transparent)" @click.stop
                      >
                        <Icon icon="carbon:information" :width="14" :height="14" />
                      </span>
                    </TooltipTrigger>
                    <TooltipContent class="!rounded p-3">
                      <div class="text-xs gap-x-4 gap-y-1.5 grid grid-cols-4">
                        <template v-if="task.min !== undefined">
                          <span class="text-muted-foreground">最小</span>
                          <span class="font-medium font-number">{{ Math.round(task.min) }} ms</span>
                        </template>
                        <template v-if="task.max !== undefined">
                          <span class="text-muted-foreground">最大</span>
                          <span class="font-medium font-number">{{ Math.round(task.max) }} ms</span>
                        </template>
                        <template v-if="task.avg !== undefined">
                          <span class="text-muted-foreground">平均</span>
                          <span class="font-medium font-number">{{ Math.round(task.avg) }} ms</span>
                        </template>
                        <template v-if="task.latest !== undefined">
                          <span class="text-muted-foreground">最新</span>
                          <span class="font-medium font-number">{{ Math.round(task.latest) }} ms</span>
                        </template>
                        <template v-if="task.p50 !== undefined">
                          <span class="text-muted-foreground">P50</span>
                          <span class="font-medium font-number">{{ Math.round(task.p50) }} ms</span>
                        </template>
                        <template v-if="task.p99 !== undefined">
                          <span class="text-muted-foreground">P99</span>
                          <span class="font-medium font-number">{{ Math.round(task.p99) }} ms</span>
                        </template>
                        <template v-if="task.p99_p50_ratio !== undefined">
                          <span class="text-muted-foreground">波动率</span>
                          <span class="font-medium font-number">{{ task.p99_p50_ratio.toFixed(2) }}</span>
                        </template>
                        <template v-if="task.interval !== undefined">
                          <span class="text-muted-foreground">间隔</span>
                          <span class="font-medium font-number">{{ task.interval }}s</span>
                        </template>
                        <template v-if="task.type">
                          <span class="text-muted-foreground">类型</span>
                          <span class="font-medium font-number">{{ task.type.toUpperCase() }}</span>
                        </template>
                        <template v-if="task.total !== undefined">
                          <span class="text-muted-foreground">总数</span>
                          <span class="font-medium font-number">{{ task.total }}</span>
                        </template>
                      </div>
                    </TooltipContent>
                  </Tooltip>
                </div>
              </TooltipProvider>
              <div class="text-xs mt-1 flex gap-1.5 items-center text-muted-foreground">
                <span class="font-medium font-number" title="平均延迟">
                  {{ task.avg !== undefined ? `${Math.round(task.avg)}ms` : '-' }}
                </span>
                <span class="opacity-60">·</span>
                <span class="font-number" title="丢包率">{{ task.loss.toFixed(2) }}%</span>
                <template v-if="task.p99_p50_ratio !== undefined">
                  <span class="opacity-60">·</span>
                  <span class="font-number" title="波动率">{{ task.p99_p50_ratio.toFixed(2) }}</span>
                </template>
              </div>
            </div>
          </div>
        </div>

        <!-- 平滑峰值开关 + 全选/全不选 -->
        <div class="flex flex-wrap gap-4 items-center py-2 justify-between">
          <TooltipProvider>
            <div class="flex gap-2 items-center">
              <Button :variant="cutPeak ? 'default' : 'outline'" size="sm" @click="cutPeak = !cutPeak">
                平滑峰值
              </Button>
              <Tooltip>
                <TooltipTrigger as-child>
                  <span
                    class="text-sm opacity-50 cursor-help transition-opacity hover:opacity-100 inline-flex text-muted-foreground"
                  >
                    <Icon icon="carbon:information" :width="14" :height="14" />
                  </span>
                </TooltipTrigger>
                <TooltipContent>
                  <span>使用 EWMA 算法平滑数据并过滤突变值</span>
                </TooltipContent>
              </Tooltip>
            </div>
          </TooltipProvider>
          <div class="flex gap-2 items-center">
            <Button variant="ghost" size="sm" @click="showAllTasks">
              全选
            </Button>
            <Button variant="ghost" size="sm" @click="hideAllTasks">
              全不选
            </Button>
          </div>
        </div>

        <!-- 图表 -->
        <div class="h-80 bg-background/50 p-4 rounded-md">
          <VChart :option="pingChartOption" autoresize />
        </div>
      </template>
    </Spinner>
  </div>
</template>
