// src/components/PingChart.vue
<script setup lang="ts">
import { Icon } from '@iconify/vue'
import dayjs from 'dayjs'
import { computed, onBeforeUnmount, onMounted, ref, shallowRef, watch } from 'vue'
import VChart from 'vue-echarts'
import { Button } from '@/components/ui/button'
import { Empty } from '@/components/ui/empty'
import { Spinner } from '@/components/ui/spinner'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip'
import { useAppStore } from '@/stores/app'
import { cutPeakValues, interpolateNullsLinear } from '@/utils/recordHelper'
import { getSharedRpc } from '@/utils/rpc'
import '@/utils/echarts' // 共享 ECharts 配置

const props = defineProps<{
  uuid: string
}>()

const appStore = useAppStore()
const isDark = computed(() => appStore.isDark)
// 使用共享的 RPC 实例，避免重复创建连接
const rpc = getSharedRpc()

// 图表主题相关颜色
const chartThemeColors = computed(() => ({
  text: isDark.value ? 'rgba(255, 255, 255, 0.85)' : 'rgba(0, 0, 0, 0.85)',
  textSecondary: isDark.value ? 'rgba(255, 255, 255, 0.55)' : 'rgba(0, 0, 0, 0.55)',
  textTertiary: isDark.value ? 'rgba(255, 255, 255, 0.35)' : 'rgba(0, 0, 0, 0.35)',
  borderColor: isDark.value ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.06)',
  splitLineColor: isDark.value ? 'rgba(255, 255, 255, 0.06)' : 'rgba(0, 0, 0, 0.06)',
  tooltipBg: isDark.value ? 'rgba(40, 40, 40, 0.95)' : 'rgba(255, 255, 255, 0.8)',
  tooltipShadow: isDark.value ? 'rgba(0, 0, 0, 0.4)' : 'rgba(0, 0, 0, 0.06)',
  crosshairColor: isDark.value ? 'rgba(255, 255, 255, 0.15)' : 'rgba(0, 0, 0, 0.1)',
}))

// 优化后的图表配色方案（多任务时使用）
const chartColors = [
  '#FF6B6B', // 珊瑚红
  '#4ECDC4', // 青绿色
  '#A78BFA', // 紫罗兰
  '#60A5FA', // 天蓝色
  '#FFB347', // 琥珀黄
  '#F472B6', // 粉红色
  '#34D399', // 翠绿色
  '#FB923C', // 橙色
]

// 从 publicSettings 获取记录保留时间
const maxPingRecordPreserveTime = computed(() => appStore.publicSettings?.ping_record_preserve_time || 168)

// 视图选项
const presetViews = [
  { label: '1 小时', hours: 1 },
  { label: '6 小时', hours: 6 },
  { label: '12 小时', hours: 12 },
  { label: '1 天', hours: 24 },
]

// 可用视图列表
const availableViews = computed(() => {
  const views: { label: string, hours: number }[] = []
  const maxHours = maxPingRecordPreserveTime.value

  for (const v of presetViews) {
    if (maxHours >= v.hours) {
      views.push(v)
    }
  }

  const maxPreset = presetViews.at(-1)
  if (maxPreset && maxHours > maxPreset.hours) {
    const label = maxHours % 24 === 0
      ? `${Math.floor(maxHours / 24)} 天`
      : `${maxHours} 小时`
    views.push({ label, hours: maxHours })
  }
  else if (maxHours > 1 && !presetViews.some(v => v.hours === maxHours)) {
    const label = maxHours % 24 === 0
      ? `${Math.floor(maxHours / 24)} 天`
      : `${maxHours} 小时`
    views.push({ label, hours: maxHours })
  }

  return views
})

// 当前选中的视图
const selectedView = ref<string>('')
const selectedHours = computed(() => {
  const view = availableViews.value.find(v => v.label === selectedView.value)
  return view?.hours || 1
})

// 初始化默认视图
watch(availableViews, (views) => {
  const firstView = views[0]
  if (firstView && !selectedView.value) {
    selectedView.value = firstView.label
  }
}, { immediate: true })

// ==================== 类型定义 ====================

interface PingRecord {
  client: string
  task_id: number
  time: string
  value: number
}

interface TaskInfo {
  id: number
  name: string
  interval: number
  loss: number
  p99?: number
  p50?: number
  p99_p50_ratio?: number
  min?: number
  max?: number
  avg?: number
  latest?: number
  total?: number
  type?: string
}

interface PingRecordsResponse {
  count: number
  records: PingRecord[]
  tasks?: TaskInfo[]
  from?: string
  to?: string
}

// 数据状态
const remoteData = shallowRef<PingRecord[]>([])
const tasks = shallowRef<TaskInfo[]>([])
const loading = ref(false)
const error = ref<string | null>(null)

// 任务选择
const selectedTaskIds = ref<number[]>([])
const cutPeak = ref(false)
const showLoss = ref(true)
const isTouchTooltipMode = ref(false)
const activeTaskTooltipId = ref<number | null>(null)
const smoothInfoTooltipOpen = ref(false)

const chartMargin = { top: 30, right: 24, bottom: 52, left: 56 }
let coarsePointerMediaQuery: MediaQueryList | null = null

const mergeToleranceMs = computed(() => {
  const taskIntervals = tasks.value
    .map(t => t.interval)
    .filter((v): v is number => typeof v === 'number' && v > 0)

  const fallbackIntervalSec = taskIntervals.length ? Math.min(...taskIntervals) : 60
  return Math.min(
    6000,
    Math.max(800, Math.floor(fallbackIntervalSec * 1000 * 0.25)),
  )
})

function syncTouchTooltipMode() {
  if (typeof window === 'undefined') {
    isTouchTooltipMode.value = false
    return
  }

  const hasCoarsePointer = window.matchMedia('(pointer: coarse)').matches
  const hasTouchPoints = typeof navigator !== 'undefined' && navigator.maxTouchPoints > 0
  isTouchTooltipMode.value = hasCoarsePointer || hasTouchPoints
}

function setTaskTooltipOpen(taskId: number, open: boolean) {
  activeTaskTooltipId.value = open ? taskId : activeTaskTooltipId.value === taskId ? null : activeTaskTooltipId.value
}

function toggleTaskTooltip(taskId: number) {
  if (!isTouchTooltipMode.value)
    return

  activeTaskTooltipId.value = activeTaskTooltipId.value === taskId ? null : taskId
  smoothInfoTooltipOpen.value = false
}

function toggleSmoothInfoTooltip() {
  if (!isTouchTooltipMode.value)
    return

  smoothInfoTooltipOpen.value = !smoothInfoTooltipOpen.value
  if (smoothInfoTooltipOpen.value) {
    activeTaskTooltipId.value = null
  }
}

// ==================== 数据获取 ====================

async function fetchRecords() {
  if (!props.uuid)
    return

  loading.value = true
  error.value = null

  try {
    const result = await rpc.getClient().call<PingRecordsResponse>('common:getRecords', {
      uuid: props.uuid,
      type: 'ping',
      hours: selectedHours.value,
    })

    const records = result?.records || []
    records.sort((a, b) => dayjs(a.time).valueOf() - dayjs(b.time).valueOf())

    remoteData.value = records
    tasks.value = result?.tasks || []

    if (tasks.value.length > 0 && selectedTaskIds.value.length === 0) {
      selectedTaskIds.value = tasks.value.map(t => t.id)
    }
  }
  catch (err) {
    error.value = err instanceof Error ? err.message : '获取数据失败'
    remoteData.value = []
    tasks.value = []
  }
  finally {
    loading.value = false
  }
}

// ==================== 数据处理 ====================

const mergedData = computed(() => {
  const data = remoteData.value
  if (!data.length)
    return []

  const toleranceMs = mergeToleranceMs.value

  const grouped: Map<number, Record<string, unknown>> = new Map()
  const anchors: number[] = []

  for (const rec of data) {
    const ts = dayjs(rec.time).valueOf()
    let anchor: number | null = null

    for (const a of anchors) {
      if (Math.abs(a - ts) <= toleranceMs) {
        anchor = a
        break
      }
    }

    const useTs = anchor ?? ts
    if (!grouped.has(useTs)) {
      grouped.set(useTs, { time: dayjs(useTs).toISOString() })
      if (anchor === null) {
        anchors.push(useTs)
      }
    }

    const group = grouped.get(useTs)!
    group[rec.task_id] = rec.value < 0 ? null : rec.value
  }

  const merged = Array.from(grouped.values()).sort(
    (a, b) => dayjs(a.time as string).valueOf() - dayjs(b.time as string).valueOf(),
  )

  const hours = selectedHours.value
  const lastItem = merged.at(-1)
  const lastTs = lastItem ? dayjs(lastItem.time as string).valueOf() : dayjs().valueOf()
  const fromTs = lastTs - hours * 3600_000

  let startIdx = 0
  for (let i = 0; i < merged.length; i++) {
    const item = merged[i]
    if (!item)
      continue
    const ts = dayjs(item.time as string).valueOf()
    if (ts >= fromTs) {
      startIdx = Math.max(0, i - 1)
      break
    }
  }

  return merged.slice(startIdx)
})

const chartData = computed(() => {
  let data = mergedData.value
  const selectedKeys = selectedTaskIds.value.map(String)

  if (selectedKeys.length === 0)
    return []

  if (cutPeak.value) {
    data = cutPeakValues(data, selectedKeys)
  }

  if (selectedKeys.length > 0 && data.length > 0) {
    data = interpolateNullsLinear(data, selectedKeys, {
      maxGapMultiplier: 6,
      minCapMs: 2 * 60_000,
      maxCapMs: 30 * 60_000,
    })
  }

  return data
})

// ==================== 工具函数 ====================

function formatTime(time: string, showDate: boolean): string {
  const date = dayjs(time)
  if (showDate) {
    return date.format('M/D HH:mm')
  }
  return date.format('HH:mm')
}

function formatTimeForTooltip(time: string, hours: number): string {
  const date = dayjs(time)
  if (hours < 24) {
    return date.format('HH:mm:ss')
  }
  return date.format('MM/DD HH:mm')
}

const showDateInAxis = computed(() => selectedHours.value >= 24)

// ==================== 任务选择 ====================

// 获取任务颜色（根据任务在完整列表中的索引）
function getTaskColor(taskId: number): string {
  const taskIndex = tasks.value.findIndex(t => t.id === taskId)
  const safeIndex = Math.max(0, taskIndex % chartColors.length)
  return chartColors[safeIndex]!
}

// 最新值统计（从服务端 tasks 获取，保持颜色顺序）
const latestValues = computed(() => {
  if (!tasks.value.length)
    return []

  const latestMap = new Map<number, number | null>()
  for (const task of tasks.value) {
    for (let i = remoteData.value.length - 1; i >= 0; i--) {
      const rec = remoteData.value[i]
      if (rec && rec.task_id === task.id && rec.value >= 0) {
        latestMap.set(task.id, rec.value)
        break
      }
    }
  }

  return tasks.value.map((task, idx) => {
    const safeIdx = Math.max(0, idx % chartColors.length)
    return {
      ...task,
      latestValue: latestMap.get(task.id) ?? null,
      color: chartColors[safeIdx]!,
    }
  })
})

const selectedTasks = computed(() => {
  return tasks.value.filter(t => selectedTaskIds.value.includes(t.id))
})

const packetLossMarkers = computed(() => {
  const data = mergedData.value
  const markers = new Map<number, number[]>()

  if (!data.length || !selectedTasks.value.length)
    return markers

  const chartTimes = data.map(item => dayjs(item.time as string).valueOf())
  const toleranceMs = mergeToleranceMs.value

  for (const task of selectedTasks.value) {
    const points = new Set<number>()
    const taskLossRecords = remoteData.value.filter(rec => rec.task_id === task.id && rec.value < 0)

    for (const record of taskLossRecords) {
      const lossTs = dayjs(record.time).valueOf()
      let matchedIndex = -1

      for (let i = 0; i < chartTimes.length; i++) {
        const chartTs = chartTimes[i]
        if (chartTs === undefined)
          continue

        if (Math.abs(chartTs - lossTs) <= toleranceMs) {
          matchedIndex = i
          break
        }
      }

      if (matchedIndex >= 0) {
        points.add(matchedIndex)
      }
    }

    markers.set(task.id, Array.from(points).sort((a, b) => a - b))
  }

  return markers
})

// 切换任务选中状态
function toggleTask(taskId: number) {
  if (selectedTaskIds.value.includes(taskId)) {
    selectedTaskIds.value = selectedTaskIds.value.filter(id => id !== taskId)
  }
  else {
    selectedTaskIds.value = [...selectedTaskIds.value, taskId]
  }
}

function showAllTasks() {
  selectedTaskIds.value = tasks.value.map(t => t.id)
}

function hideAllTasks() {
  selectedTaskIds.value = []
}

// ==================== 图表配置 ====================

// 通用 Tooltip 配置
const baseTooltipConfig = computed(() => ({
  trigger: 'axis' as const,
  confine: false,
  backgroundColor: chartThemeColors.value.tooltipBg,
  borderColor: 'transparent',
  borderWidth: 0,
  borderRadius: 6,
  textStyle: {
    color: chartThemeColors.value.text,
    fontSize: 12,
    lineHeight: 20,
  },
  extraCssText: `backdrop-filter: blur(5px);z-index:9;box-shadow:0 0 0 1px ${chartThemeColors.value.tooltipShadow}, 0 0 16px ${chartThemeColors.value.tooltipShadow}`,
  axisPointer: {
    type: 'cross' as const,
    crossStyle: {
      color: chartThemeColors.value.textTertiary,
    },
    lineStyle: {
      color: chartThemeColors.value.crosshairColor,
      width: 1,
      type: 'dashed' as const,
    },
    shadowStyle: {
      color: chartThemeColors.value.crosshairColor,
    },
  },
}))

const pingChartOption = computed(() => {
  const taskList = selectedTasks.value
  const data = chartData.value
  const hours = selectedHours.value

  // 构建 series，确保颜色与卡片一致
  const series = taskList.map((task) => {
    const color = getTaskColor(task.id)
    const lossMarkerIndexes = packetLossMarkers.value.get(task.id) || []
    return {
      name: task.name,
      type: 'line' as const,
      data: data.map(d => d[task.id] as number | null ?? null),
      smooth: cutPeak.value ? 0.6 : 0.1,
      showSymbol: false,
      connectNulls: false,
      lineStyle: { width: 1.5, color, cap: 'round' as const },
      itemStyle: { color }, // 确保 symbol 颜色一致
      markLine: showLoss.value && lossMarkerIndexes.length
        ? {
            silent: true,
            symbol: ['none', 'none'],
            animation: false,
            label: { show: false },
            lineStyle: {
              color,
              width: 1,
              type: 'solid' as const,
              opacity: 0.55,
            },
            data: lossMarkerIndexes.map(index => ({
              xAxis: index,
            })),
          }
        : undefined,
    }
  })

  // 颜色映射表（用于 Tooltip）
  const colorMap = new Map<number, string>()
  tasks.value.forEach((task, idx) => {
    const safeIdx = Math.max(0, idx % chartColors.length)
    colorMap.set(task.id, chartColors[safeIdx]!)
  })

  return {
    animation: false,
    // 全局颜色设置（用于图例等）
    color: tasks.value.map((_, idx) => {
      const safeIdx = Math.max(0, idx % chartColors.length)
      return chartColors[safeIdx]!
    }),
    tooltip: {
      ...baseTooltipConfig.value,
      formatter: (params: unknown) => {
        const p = params as Array<{ seriesName: string, value: number | null, dataIndex: number }>
        if (!p.length)
          return ''
        const firstParam = p[0]
        if (!firstParam)
          return ''
        const rowData = data[firstParam.dataIndex]
        if (!rowData)
          return ''

        const time = rowData.time as string
        const timeStr = formatTimeForTooltip(time, hours)
        let html = `<div style="font-weight:600;margin-bottom:6px;color:${chartThemeColors.value.textSecondary}">${timeStr}</div>`
        html += '<div style="display:flex;flex-direction:column;gap:4px">'

        // 按延迟值排序显示
        const sortedParams = [...p].sort((a, b) => (a.value ?? 0) - (b.value ?? 0))

        for (const item of sortedParams) {
          if (item.value !== null && item.value !== undefined) {
            // 通过任务名找到对应的任务ID，再获取颜色
            const task = tasks.value.find(t => t.name === item.seriesName)
            const color = task ? colorMap.get(task.id) || chartColors[0] : chartColors[0]
            const colorDot = `<span style="display:inline-block;width:8px;height:8px;border-radius:50%;background:${color};margin-right:8px;flex-shrink:0"></span>`
            html += `<div style="display:flex;align-items:center">${colorDot}<span style="flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${item.seriesName}</span><span style="margin-left:auto;font-weight:600;margin-left:16px;font-variant-numeric:tabular-nums">${Math.round(item.value)} ms</span></div>`
          }
        }
        html += '</div>'
        return html
      },
    },
    legend: {
      type: 'scroll',
      bottom: 0,
      itemWidth: 12,
      itemHeight: 12,
      itemGap: 16,
      icon: 'roundRect',
      textStyle: { fontSize: 11, color: chartThemeColors.value.textSecondary },
      data: taskList.map(t => t.name),
    },
    grid: chartMargin,
    xAxis: {
      type: 'category',
      data: data.map(d => formatTime(d.time as string, showDateInAxis.value)),
      axisLabel: {
        fontSize: 11,
        color: chartThemeColors.value.textSecondary,
        margin: 12,
      },
      axisLine: {
        show: true,
        lineStyle: { color: chartThemeColors.value.borderColor, width: 1 },
      },
      axisTick: { show: false },
      boundaryGap: false,
    },
    yAxis: {
      type: 'value',
      name: '延迟 (ms)',
      nameTextStyle: { color: chartThemeColors.value.textSecondary },
      axisLabel: { fontSize: 11, color: chartThemeColors.value.textSecondary, formatter: '{value}' },
      axisLine: { show: false },
      axisTick: { show: false },
      splitLine: {
        lineStyle: {
          color: chartThemeColors.value.splitLineColor,
          type: 'dashed' as const,
        },
      },
    },
    series,
  }
})

// ==================== 生命周期 ====================

watch(selectedView, () => {
  selectedTaskIds.value = []
  fetchRecords()
})

watch(() => props.uuid, () => {
  remoteData.value = []
  tasks.value = []
  selectedTaskIds.value = []
  activeTaskTooltipId.value = null
  smoothInfoTooltipOpen.value = false
  fetchRecords()
})

onMounted(() => {
  syncTouchTooltipMode()
  coarsePointerMediaQuery = window.matchMedia('(pointer: coarse)')
  coarsePointerMediaQuery.addEventListener('change', syncTouchTooltipMode)

  const firstView = availableViews.value[0]
  if (firstView && !selectedView.value) {
    selectedView.value = firstView.label
  }
  fetchRecords()
})

onBeforeUnmount(() => {
  coarsePointerMediaQuery?.removeEventListener('change', syncTouchTooltipMode)
})
</script>

<template>
  <div class="flex flex-col gap-4">
    <!-- 时间选择器 -->
    <Tabs v-model="selectedView" class="w-full items-center">
      <div class="min-w-0 flex-1 overflow-x-auto rounded-sm pointer-events-auto">
        <TabsList class="w-max h-8 bg-background/50 backdrop-blur-xl rounded-md">
          <TabsTrigger
            v-for="view in availableViews" :key="view.label" :value="view.label"
            class="h-6.5 flex-none shrink-0 text-xs border-none data-[state=active]:text-green-600 shadow-none rounded-sm"
          >
            {{ view.label }}
          </TabsTrigger>
        </TabsList>
      </div>
      <div class="md:flex-1" />
      <div class="flex gap-2 items-center">
        <Button
          variant="ghost" size="xs" class="h-7 rounded-sm bg-background/50 hover:bg-background border-none"
          :class="selectedTaskIds.length === tasks.length ? 'shadow-[0_0_0_2px] shadow-green-600/10 text-green-600' : ''"
          @click="showAllTasks"
        >
          全选
        </Button>
        <Button
          variant="ghost" size="xs" class="h-7 rounded-sm bg-background/50 hover:bg-background border-none"
          :class="!selectedTaskIds.length && 'shadow-[0_0_0_2px] shadow-green-600/10 text-green-600'"
          @click="hideAllTasks"
        >
          全不选
        </Button>
      </div>
    </Tabs>

    <!-- 内容区域 -->
    <Spinner :show="loading" content-class="flex flex-col gap-4">
      <div v-if="error" class="text-red-500 py-8 text-center">
        {{ error }}
      </div>
      <div v-else-if="tasks.length === 0 && !loading" class="py-8">
        <Empty description="暂无延迟数据" />
      </div>

      <template v-else>
        <!-- 最新值统计卡片（可点击切换选中状态） -->
        <div
          v-if="latestValues.length > 0" class="gap-3 grid"
          style="grid-template-columns: repeat(auto-fit, minmax(180px, 1fr))"
        >
          <div
            v-for="task in latestValues" :key="task.id"
            class="p-2 rounded-md bg-background/50 hover:bg-background hover:shadow-[0_0_0_2px] hover:shadow-primary/10 flex gap-3 cursor-pointer select-none transition-all items-center"
            :class="[!selectedTaskIds.includes(task.id) && 'opacity-30']"
            :onmouseover="(e: MouseEvent) => ((e.currentTarget as HTMLElement).style.borderColor = task.color)"
            :onmouseout="(e: MouseEvent) => ((e.currentTarget as HTMLElement).style.borderColor = '')"
            @click="toggleTask(task.id)"
          >
            <div class="flex-1 min-w-0">
              <TooltipProvider>
                <div class="flex gap-2 items-center">
                  <div class="rounded h-4 w-1" :style="{ backgroundColor: task.color }" />
                  <span class="text-sm font-semibold truncate">{{ task.name }}</span>
                  <div class="flex-1" />
                  <Tooltip
                    :open="isTouchTooltipMode ? activeTaskTooltipId === task.id : undefined"
                    @update:open="(open) => setTaskTooltipOpen(task.id, open)"
                  >
                    <TooltipTrigger as-child>
                      <Button variant="ghost" size="icon-xs" class="text-slate-500" @click.stop="toggleTaskTooltip(task.id)">
                        <Icon icon="carbon:information" :width="14" :height="14" />
                      </Button>
                    </TooltipTrigger>
                    <TooltipContent class="!rounded p-3">
                      <div class="text-xs gap-x-4 gap-y-1.5 grid grid-cols-4">
                        <template v-if="task.min !== undefined">
                          <span class="text-muted-foreground">最小</span>
                          <span class="font-medium">{{ Math.round(task.min) }} ms</span>
                        </template>
                        <template v-if="task.max !== undefined">
                          <span class="text-muted-foreground">最大</span>
                          <span class="font-medium">{{ Math.round(task.max) }} ms</span>
                        </template>
                        <template v-if="task.avg !== undefined">
                          <span class="text-muted-foreground">平均</span>
                          <span class="font-medium">{{ Math.round(task.avg) }} ms</span>
                        </template>
                        <template v-if="task.latest !== undefined">
                          <span class="text-muted-foreground">最新</span>
                          <span class="font-medium">{{ Math.round(task.latest) }} ms</span>
                        </template>
                        <template v-if="task.p50 !== undefined">
                          <span class="text-muted-foreground">P50</span>
                          <span class="font-medium">{{ Math.round(task.p50) }} ms</span>
                        </template>
                        <template v-if="task.p99 !== undefined">
                          <span class="text-muted-foreground">P99</span>
                          <span class="font-medium">{{ Math.round(task.p99) }} ms</span>
                        </template>
                        <template v-if="task.p99_p50_ratio !== undefined">
                          <span class="text-muted-foreground">波动率</span>
                          <span class="font-medium">{{ task.p99_p50_ratio.toFixed(2) }}</span>
                        </template>
                        <template v-if="task.interval !== undefined">
                          <span class="text-muted-foreground">间隔</span>
                          <span class="font-medium">{{ task.interval }}s</span>
                        </template>
                        <template v-if="task.type">
                          <span class="text-muted-foreground">类型</span>
                          <span class="font-medium">{{ task.type.toUpperCase() }}</span>
                        </template>
                        <template v-if="task.total !== undefined">
                          <span class="text-muted-foreground">总数</span>
                          <span class="font-medium">{{ task.total }}</span>
                        </template>
                      </div>
                    </TooltipContent>
                  </Tooltip>
                </div>
              </TooltipProvider>
              <div class="text-xs mt-1 flex gap-1.5 items-center text-muted-foreground">
                <span class="font-medium" title="平均延迟">
                  {{ task.avg !== undefined ? `${Math.round(task.avg)}ms` : '-' }}
                </span>
                <span class="opacity-60">·</span>
                <span title="丢包率">{{ task.loss.toFixed(2) }}%</span>
                <template v-if="task.p99_p50_ratio !== undefined">
                  <span class="opacity-60">·</span>
                  <span title="波动率">{{ task.p99_p50_ratio.toFixed(2) }}</span>
                </template>
              </div>
            </div>
          </div>
        </div>

        <div class="flex flex-wrap gap-2 items-center py-2">
          <!-- 丢包可视化开关 -->
          <Button
            variant="ghost" size="xs" class="h-7 rounded-sm bg-background/50 hover:bg-background border-none"
            :class="showLoss && 'shadow-[0_0_0_2px] shadow-green-600/10 text-green-600'" @click="showLoss = !showLoss"
          >
            丢包可视化
          </Button>
          <!-- 平滑峰值开关 -->
          <TooltipProvider>
            <div class="flex gap-2 items-center">
              <Button
                variant="ghost" size="xs" class="h-7 rounded-sm bg-background/50 hover:bg-background border-none"
                :class="cutPeak && 'shadow-[0_0_0_2px] shadow-green-600/10 text-green-600'" @click="cutPeak = !cutPeak"
              >
                平滑峰值
              </Button>
              <Tooltip
                :open="isTouchTooltipMode ? smoothInfoTooltipOpen : undefined"
                @update:open="(open) => smoothInfoTooltipOpen = open"
              >
                <TooltipTrigger as-child>
                  <Button variant="ghost" size="icon-xs" class="text-slate-500" @click.stop="toggleSmoothInfoTooltip">
                    <Icon icon="carbon:information" :width="14" :height="14" />
                  </Button>
                </TooltipTrigger>
                <TooltipContent>
                  <span>使用 EWMA 算法平滑数据并过滤突变值</span>
                </TooltipContent>
              </Tooltip>
            </div>
          </TooltipProvider>
        </div>

        <!-- 图表 -->
        <div class="h-80 bg-background/50 p-4 rounded-md">
          <VChart :option="pingChartOption" autoresize />
        </div>
      </template>
    </Spinner>
  </div>
</template>

// src/components/PingChart.tsx
'use client'

import type { EChartsOption } from 'echarts'
import dayjs from 'dayjs'
import { useEffect, useMemo, useState } from 'react'
import EChart from '@/components/EChart'
import { Button } from '@/components/ui/button'
import { Empty } from '@/components/ui/empty'
import { Skeleton } from '@/components/ui/skeleton'
import { Tabs, TabsList, TabsTab } from '@/components/ui/tabs'
import { useAppDerived, useAppStore } from '@/stores/app'
import { cutPeakValues, interpolateNullsLinear } from '@/utils/recordHelper'
import { getSharedRpc } from '@/utils/rpc'

interface PingRecord {
  client: string
  task_id: number
  time: string
  value: number
}

interface TaskInfo {
  id: number
  name: string
  interval: number
  loss: number
  avg?: number
}

interface PingRecordsResponse {
  count: number
  records: PingRecord[]
  tasks?: TaskInfo[]
}

const presetViews = [
  { label: '1 小时', hours: 1 },
  { label: '6 小时', hours: 6 },
  { label: '12 小时', hours: 12 },
  { label: '1 天', hours: 24 },
]

const chartColors = ['#FF6B6B', '#4ECDC4', '#A78BFA', '#60A5FA', '#FFB347', '#F472B6', '#34D399', '#FB923C']
const chartMargin = { top: 30, right: 24, bottom: 52, left: 56 }
const pingTaskSkeletonItems = ['unicom', 'mobile', 'telecom', 'cloudflare']
const pingChartSkeletonPaths = [
  'M0 154 C58 134 94 146 137 126 C184 104 229 109 272 118 C325 130 361 95 416 104 C476 114 514 83 640 96',
  'M0 112 C52 119 94 91 145 99 C202 108 238 134 292 122 C343 111 374 143 426 130 C493 114 543 122 640 104',
  'M0 183 C78 172 109 189 162 176 C217 162 264 181 314 169 C372 155 413 171 466 151 C526 129 574 143 640 122',
]

function formatTime(time: string, showDate: boolean): string {
  const date = dayjs(time)
  return showDate ? date.format('M/D HH:mm') : date.format('HH:mm')
}

function formatTimeForTooltip(time: string, hours: number): string {
  const date = dayjs(time)
  return hours < 24 ? date.format('HH:mm:ss') : date.format('MM/DD HH:mm')
}

function escapeHtml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll('\'', '&#39;')
}

interface TooltipParam {
  seriesName?: string
  value?: unknown
  dataIndex?: number
}

function normalizeTooltipParams(params: unknown): TooltipParam[] {
  if (Array.isArray(params))
    return params as TooltipParam[]
  if (params && typeof params === 'object')
    return [params as TooltipParam]
  return []
}

function getNumericTooltipValue(value: unknown): number | null {
  if (typeof value === 'number' && Number.isFinite(value))
    return value
  if (Array.isArray(value)) {
    const candidate = value.at(-1)
    if (typeof candidate === 'number' && Number.isFinite(candidate))
      return candidate
  }
  return null
}

export default function PingChart({ uuid, className }: { uuid: string, className?: string }) {
  const publicSettings = useAppStore(state => state.publicSettings)
  const { isDark } = useAppDerived()
  const maxHours = publicSettings?.ping_record_preserve_time || 168
  const views = presetViews.filter(view => maxHours >= view.hours)
  const [selectedView, setSelectedView] = useState(views[0]?.label ?? '1 小时')
  const selectedHours = views.find(view => view.label === selectedView)?.hours ?? 1
  const [records, setRecords] = useState<PingRecord[]>([])
  const [tasks, setTasks] = useState<TaskInfo[]>([])
  const [selectedTaskIds, setSelectedTaskIds] = useState<number[]>([])
  const [showDelay, setShowDelay] = useState(true)
  const [showLoss, setShowLoss] = useState(true)
  const [cutPeak, setCutPeak] = useState(false)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    let cancelled = false
    async function fetchRecords() {
      setLoading(true)
      setError(null)
      try {
        const result = await getSharedRpc().getClient().call<PingRecordsResponse>('common:getRecords', {
          uuid,
          type: 'ping',
          hours: selectedHours,
        })
        const nextRecords = (result.records ?? []).sort((a, b) => dayjs(a.time).valueOf() - dayjs(b.time).valueOf())
        const nextTasks = result.tasks ?? []
        if (!cancelled) {
          setRecords(nextRecords)
          setTasks(nextTasks)
          setSelectedTaskIds(current => current.length ? current.filter(id => nextTasks.some(task => task.id === id)) : nextTasks.map(task => task.id))
        }
      }
      catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : '获取数据失败')
          setRecords([])
          setTasks([])
        }
      }
      finally {
        if (!cancelled)
          setLoading(false)
      }
    }
    void fetchRecords()
    return () => {
      cancelled = true
    }
  }, [selectedHours, uuid])

  const mergeToleranceMs = useMemo(() => {
    const taskIntervals = tasks
      .map(task => task.interval)
      .filter(interval => typeof interval === 'number' && interval > 0)

    const fallbackIntervalSec = taskIntervals.length ? Math.min(...taskIntervals) : 60

    return Math.min(
      6000,
      Math.max(800, Math.floor(fallbackIntervalSec * 1000 * 0.25)),
    )
  }, [tasks])

  const mergedData = useMemo(() => {
    if (!records.length)
      return []

    const grouped = new Map<number, Record<string, number | string | null>>()
    const anchors: number[] = []

    for (const record of records) {
      const ts = dayjs(record.time).valueOf()
      let anchor: number | null = null

      for (const candidate of anchors) {
        if (Math.abs(candidate - ts) <= mergeToleranceMs) {
          anchor = candidate
          break
        }
      }

      const useTs = anchor ?? ts
      if (!grouped.has(useTs)) {
        grouped.set(useTs, { time: dayjs(useTs).toISOString() })
        if (anchor === null)
          anchors.push(useTs)
      }

      const row = grouped.get(useTs)
      if (row)
        row[String(record.task_id)] = record.value < 0 ? null : record.value
    }

    const merged = Array.from(grouped.values()).sort((a, b) => dayjs(a.time as string).valueOf() - dayjs(b.time as string).valueOf())
    const lastItem = merged.at(-1)
    const lastTs = lastItem ? dayjs(lastItem.time as string).valueOf() : dayjs().valueOf()
    const fromTs = lastTs - selectedHours * 3600_000

    let startIdx = 0
    for (let i = 0; i < merged.length; i++) {
      const item = merged[i]
      if (!item)
        continue
      const ts = dayjs(item.time as string).valueOf()
      if (ts >= fromTs) {
        startIdx = Math.max(0, i - 1)
        break
      }
    }

    return merged.slice(startIdx)
  }, [mergeToleranceMs, records, selectedHours])

  const selectedKeys = useMemo(() => selectedTaskIds.map(String), [selectedTaskIds])

  const chartData = useMemo(() => {
    if (!selectedKeys.length || !mergedData.length)
      return []

    const data = cutPeak
      ? cutPeakValues(mergedData, selectedKeys)
      : mergedData

    return interpolateNullsLinear(data, selectedKeys, {
      maxGapMultiplier: 6,
      minCapMs: 2 * 60_000,
      maxCapMs: 30 * 60_000,
    }) as Record<string, number | string | null>[]
  }, [cutPeak, mergedData, selectedKeys])

  const packetLossMarkers = useMemo(() => {
    const markers = new Map<number, number[]>()
    if (!mergedData.length)
      return markers

    const chartTimes = mergedData.map(item => dayjs(item.time as string).valueOf())
    const selectedIdSet = new Set(selectedTaskIds)

    for (const task of tasks) {
      if (!selectedIdSet.has(task.id))
        continue

      const points = new Set<number>()
      const taskLossRecords = records.filter(record => record.task_id === task.id && record.value < 0)

      for (const record of taskLossRecords) {
        const lossTs = dayjs(record.time).valueOf()
        let matchedIndex = -1

        for (let i = 0; i < chartTimes.length; i++) {
          const chartTs = chartTimes[i]
          if (chartTs === undefined)
            continue

          if (Math.abs(chartTs - lossTs) <= mergeToleranceMs) {
            matchedIndex = i
            break
          }
        }

        if (matchedIndex >= 0)
          points.add(matchedIndex)
      }

      markers.set(task.id, Array.from(points).sort((a, b) => a - b))
    }

    return markers
  }, [mergeToleranceMs, mergedData, records, selectedTaskIds, tasks])

  const getTaskColor = (taskId: number) => {
    const taskIndex = tasks.findIndex(task => task.id === taskId)
    return chartColors[Math.max(0, taskIndex) % chartColors.length] ?? chartColors[0]
  }

  const allTaskIds = useMemo(() => tasks.map(task => task.id), [tasks])
  const selectedTasks = useMemo(() => tasks.filter(task => selectedTaskIds.includes(task.id)), [selectedTaskIds, tasks])

  const taskSelectionView = selectedTaskIds.length === 0
    ? 'none'
    : selectedTaskIds.length === tasks.length
      ? 'all'
      : 'custom'
  const showDateInAxis = selectedHours >= 24
  const theme = {
    text: isDark ? 'rgba(255,255,255,.85)' : 'rgba(0,0,0,.85)',
    textSecondary: isDark ? 'rgba(255,255,255,.55)' : 'rgba(0,0,0,.55)',
    textTertiary: isDark ? 'rgba(255,255,255,.35)' : 'rgba(0,0,0,.35)',
    borderColor: isDark ? 'rgba(255,255,255,.1)' : 'rgba(0,0,0,.06)',
    splitLineColor: isDark ? 'rgba(255,255,255,.06)' : 'rgba(0,0,0,.06)',
    tooltipBg: isDark ? 'rgba(40,40,40,.95)' : 'rgba(255,255,255,.88)',
    tooltipShadow: isDark ? 'rgba(0,0,0,.4)' : 'rgba(0,0,0,.06)',
    crosshairColor: isDark ? 'rgba(255,255,255,.15)' : 'rgba(0,0,0,.1)',
  }

  const option: EChartsOption = {
    animation: false,
    color: tasks.map((_, index) => chartColors[index % chartColors.length]),
    tooltip: {
      trigger: 'axis',
      confine: false,
      backgroundColor: theme.tooltipBg,
      borderColor: 'transparent',
      borderWidth: 0,
      borderRadius: 6,
      textStyle: { color: theme.text, fontSize: 12, lineHeight: 20 },
      extraCssText: `backdrop-filter: blur(5px);z-index:9;box-shadow:0 0 0 1px ${theme.tooltipShadow}, 0 0 16px ${theme.tooltipShadow}`,
      axisPointer: {
        type: 'cross',
        crossStyle: { color: theme.textTertiary },
        lineStyle: { color: theme.crosshairColor, width: 1, type: 'dashed' },
        shadowStyle: { color: theme.crosshairColor },
      },
      formatter: (params: unknown) => {
        const items = normalizeTooltipParams(params)
        const firstItem = items[0]
        if (!firstItem || firstItem.dataIndex === undefined)
          return ''

        const rowData = chartData[firstItem.dataIndex]
        if (!rowData)
          return ''

        const timeStr = formatTimeForTooltip(rowData.time as string, selectedHours)
        let html = `<div style="font-weight:600;margin-bottom:6px;color:${theme.textSecondary}">${timeStr}</div>`
        html += '<div style="display:flex;flex-direction:column;gap:4px">'

        const sortedItems = items
          .map(item => ({ ...item, numericValue: getNumericTooltipValue(item.value) }))
          .filter((item): item is TooltipParam & { numericValue: number } => item.numericValue !== null)
          .sort((a, b) => a.numericValue - b.numericValue)

        for (const item of sortedItems) {
          const task = tasks.find(candidate => candidate.name === item.seriesName)
          const color = task ? getTaskColor(task.id) : chartColors[0]
          const colorDot = `<span style="display:inline-block;width:8px;height:8px;border-radius:50%;background:${color};margin-right:8px;flex-shrink:0"></span>`
          html += `<div style="display:flex;align-items:center">${colorDot}<span style="flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${escapeHtml(item.seriesName ?? '')}</span><span style="margin-left:16px;font-weight:600;font-variant-numeric:tabular-nums">${Math.round(item.numericValue)} ms</span></div>`
        }

        html += '</div>'
        return html
      },
    },
    legend: {
      type: 'scroll',
      bottom: 0,
      itemWidth: 12,
      itemHeight: 12,
      itemGap: 16,
      icon: 'roundRect',
      textStyle: { fontSize: 11, color: theme.textSecondary },
      data: selectedTasks.map(task => task.name),
    },
    grid: chartMargin,
    xAxis: {
      type: 'category',
      data: chartData.map(row => formatTime(row.time as string, showDateInAxis)),
      boundaryGap: false,
      axisLabel: { color: theme.textSecondary, fontSize: 11, margin: 12 },
      axisLine: { show: true, lineStyle: { color: theme.borderColor, width: 1 } },
      axisTick: { show: false },
    },
    yAxis: {
      type: 'value',
      name: '延迟 (ms)',
      nameTextStyle: { color: theme.textSecondary },
      axisLabel: { color: theme.textSecondary, fontSize: 11, formatter: '{value}' },
      axisLine: { show: false },
      axisTick: { show: false },
      splitLine: { lineStyle: { color: theme.splitLineColor, type: 'dashed' } },
    },
    series: selectedTasks.map((task) => {
      const color = getTaskColor(task.id)
      const lossMarkerIndexes = packetLossMarkers.get(task.id) ?? []

      return {
        name: task.name,
        type: 'line',
        data: chartData.map(row => row[String(task.id)] as number | null ?? null),
        smooth: showDelay ? (cutPeak ? 0.6 : 0.1) : 0,
        showSymbol: false,
        connectNulls: false,
        lineStyle: { width: showDelay ? 1.5 : 0, color, cap: 'round' },
        itemStyle: { color, opacity: showDelay ? 1 : 0 },
        markLine: showLoss && lossMarkerIndexes.length
          ? {
              silent: true,
              symbol: ['none', 'none'],
              animation: false,
              label: { show: false },
              lineStyle: {
                color,
                width: 1,
                type: 'solid',
                opacity: 0.55,
              },
              data: lossMarkerIndexes.map(index => ({ xAxis: index })),
            }
          : undefined,
      }
    }),
  }

  function toggleTask(taskId: number) {
    setSelectedTaskIds(current => current.includes(taskId) ? current.filter(id => id !== taskId) : [...current, taskId])
  }

  function handleTaskSelectionChange(value: string | number | null) {
    if (value === 'all')
      setSelectedTaskIds(allTaskIds)
    if (value === 'none')
      setSelectedTaskIds([])
  }

  const getToggleButtonClass = (active: boolean) =>
    `h-7 rounded-sm bg-background/50 px-2 text-xs shadow-none hover:bg-background ${active ? 'text-primary shadow-[0_0_0_2px] shadow-primary/10' : 'text-muted-foreground'}`

  return (
    <div className={`flex flex-col gap-4 ${className ?? ''}`}>
      <Tabs value={selectedView} onValueChange={value => setSelectedView(String(value))} className="w-full">
        <div className="min-w-0 overflow-x-auto rounded-sm">
          <TabsList aria-label="延迟历史时间段">
            {views.map(view => <TabsTab key={view.label} value={view.label}>{view.label}</TabsTab>)}
          </TabsList>
        </div>
      </Tabs>
      {loading
        ? <PingChartSkeleton />
        : error
          ? <div className="py-8 text-center text-red-500">{error}</div>
          : tasks.length === 0
            ? <Empty description="暂无延迟数据" />
            : (
                <>
                  <div className="flex flex-wrap items-center justify-between gap-2">
                    <Tabs value={taskSelectionView} onValueChange={handleTaskSelectionChange}>
                      <TabsList aria-label="延迟历史任务选择">
                        <TabsTab value="all">全选</TabsTab>
                        <TabsTab value="none">全不选</TabsTab>
                      </TabsList>
                    </Tabs>
                    <div className="text-xs text-muted-foreground">
                      已选择
                      {' '}
                      {selectedTaskIds.length}
                      {' '}
                      /
                      {' '}
                      {tasks.length}
                    </div>
                  </div>
                  <div className="grid gap-3" style={{ gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))' }}>
                    {tasks.map(task => (
                      <button
                        key={task.id}
                        type="button"
                        className={`flex cursor-pointer items-center gap-3 rounded-xl border border-input bg-card p-2 text-left shadow-xs/5 transition-[background-color,border-color,opacity,box-shadow] hover:bg-accent/50 focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background focus-visible:outline-none ${!selectedTaskIds.includes(task.id) ? 'opacity-30' : ''}`}
                        onClick={() => toggleTask(task.id)}
                      >
                        <div className="h-4 w-1 rounded" style={{ backgroundColor: getTaskColor(task.id) }} />
                        <div className="min-w-0 flex-1">
                          <div className="truncate text-sm font-semibold">{task.name}</div>
                          <div className="mt-1 flex items-center gap-1.5 text-xs text-muted-foreground">
                            <span>{task.avg !== undefined ? `${Math.round(task.avg)}ms` : '-'}</span>
                            <span className="opacity-60">·</span>
                            <span>
                              {task.loss.toFixed(2)}
                              %
                            </span>
                          </div>
                        </div>
                      </button>
                    ))}
                  </div>
                  <div className="flex flex-wrap items-center gap-2">
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      aria-pressed={showDelay}
                      className={getToggleButtonClass(showDelay)}
                      onClick={() => setShowDelay(value => !value)}
                    >
                      延迟
                    </Button>
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      aria-pressed={showLoss}
                      className={getToggleButtonClass(showLoss)}
                      onClick={() => setShowLoss(value => !value)}
                    >
                      丢包
                    </Button>
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      aria-pressed={cutPeak}
                      className={getToggleButtonClass(cutPeak)}
                      onClick={() => setCutPeak(value => !value)}
                    >
                      平滑峰值
                    </Button>
                  </div>
                  <div className="vercel-card h-80 rounded-2xl bg-card p-4">
                    <EChart option={option} />
                  </div>
                </>
              )}
    </div>
  )
}

function PingChartSkeleton() {
  return (
    <>
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div className="flex gap-1 rounded-md bg-muted/50 p-1">
          <Skeleton className="h-7 w-13 rounded-sm" />
          <Skeleton className="h-7 w-16 rounded-sm" />
        </div>
        <Skeleton className="h-3 w-18" />
      </div>
      <div className="grid gap-3" style={{ gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))' }}>
        {pingTaskSkeletonItems.map(item => <PingTaskSkeletonCard key={item} />)}
      </div>
      <div className="flex flex-wrap items-center gap-2">
        <Skeleton className="h-7 w-13 rounded-sm" />
        <Skeleton className="h-7 w-13 rounded-sm" />
        <Skeleton className="h-7 w-20 rounded-sm" />
      </div>
      <div className="vercel-card h-80 rounded-2xl bg-card p-4">
        <div className="relative h-full overflow-hidden rounded-sm">
          <div className="absolute top-3 right-0 flex items-center gap-2">
            <Skeleton className="h-2.5 w-11 rounded-full" />
            <Skeleton className="h-2.5 w-14 rounded-full" />
          </div>
          <div className="absolute top-7 bottom-9 left-0 flex w-7 flex-col justify-between">
            <Skeleton className="h-2 w-5 rounded-full opacity-70" />
            <Skeleton className="h-2 w-4 rounded-full opacity-60" />
            <Skeleton className="h-2 w-5 rounded-full opacity-50" />
            <Skeleton className="h-2 w-3 rounded-full opacity-45" />
          </div>
          <div className="absolute top-7 right-0 bottom-9 left-9 overflow-hidden">
            <div className="absolute inset-0 flex flex-col justify-between">
              <span className="border-t border-dashed border-border/60" />
              <span className="border-t border-dashed border-border/45" />
              <span className="border-t border-dashed border-border/35" />
              <span className="border-t border-dashed border-border/30" />
            </div>
            <div className="absolute inset-0 flex justify-between">
              <span className="border-l border-border/30" />
              <span className="border-l border-border/20" />
              <span className="border-l border-border/20" />
              <span className="border-l border-border/20" />
              <span className="border-l border-border/30" />
            </div>
            <svg className="absolute inset-0 size-full" viewBox="0 0 640 220" preserveAspectRatio="none" aria-hidden="true">
              {pingChartSkeletonPaths.map((path, index) => (
                <path
                  key={path}
                  d={path}
                  className={`komari-skeleton-chart-line komari-skeleton-chart-line-${index + 1}`}
                />
              ))}
            </svg>
            <div className="pointer-events-none absolute inset-0 bg-gradient-to-r from-card/70 via-transparent to-card/70" />
          </div>
          <div className="absolute right-0 bottom-0 left-9 flex justify-between">
            <Skeleton className="h-2.5 w-10 rounded-full opacity-60" />
            <Skeleton className="h-2.5 w-10 rounded-full opacity-55" />
            <Skeleton className="h-2.5 w-10 rounded-full opacity-55" />
            <Skeleton className="h-2.5 w-10 rounded-full opacity-60" />
          </div>
        </div>
      </div>
    </>
  )
}

function PingTaskSkeletonCard() {
  return (
    <div className="flex items-center gap-3 rounded-xl border border-input bg-card p-2 shadow-xs/5">
      <Skeleton className="h-4 w-1 rounded" />
      <div className="min-w-0 flex-1">
        <Skeleton className="h-4 w-28" />
        <div className="mt-2 flex items-center gap-1.5">
          <Skeleton className="h-3 w-10" />
          <Skeleton className="h-3 w-1 rounded-full" />
          <Skeleton className="h-3 w-12" />
        </div>
      </div>
    </div>
  )
}
